-- PARRAINAGE HAYEVA — programme ambassadeurs (prime de 20 € par nouveau
-- client éligible, versement à partir de 200 € de solde disponible).
--
-- S'appuie sur l'existant (referral_codes, referrals, referral_events,
-- referral_settings, wallet_* pour le crédit de bienvenue du filleul) et
-- ajoute :
--   * referral_rewards           : UNE prime par parrainage (jamais plus),
--                                  cycle EN ATTENTE → VALIDÉE / NON ÉLIGIBLE ;
--   * referral_payout_requests   : demandes de versement (aucun virement
--                                  automatique — contrôle par l'administration) ;
--   * referral_ledger            : registre financier append-only ;
--   * referral_notifications     : notifications du parrain (dédupliquées).
--
-- Règle unique, appliquée exclusivement côté serveur :
--   NOUVEAU CLIENT + CODE PARRAIN + INTERVENTION TERMINÉE
--   + PAIEMENT CONFIRMÉ (facture PAYÉE, net des remboursements) >= seuil
--   = prime pour le parrain.
-- Une réservation seule ne crédite jamais rien. Montants en centimes
-- entiers (integer), jamais de flottant. Tous les paramètres (prime, seuil
-- d'éligibilité, seuil de versement, activations) sont centralisés dans
-- referral_settings.
--
-- Sécurité : aucune écriture directe possible pour anon/authenticated sur
-- les nouvelles tables (RLS sans policy d'écriture + REVOKE). Le parrain ne
-- lit ses données QUE via get_my_ambassador() (SECURITY DEFINER), qui
-- n'expose aucune donnée personnelle du filleul (référence anonyme
-- « Client #NNNN » uniquement).

-- ---------------------------------------------------------------------
-- 1) Configuration centralisée
-- ---------------------------------------------------------------------
alter table public.referral_settings
  add column if not exists min_eligible_paid_cents integer not null default 10000,
  add column if not exists min_payout_cents integer not null default 20000,
  add column if not exists ambassador_public_enabled boolean not null default false,
  add column if not exists payouts_enabled boolean not null default false;
alter table public.referral_settings add constraint referral_settings_amounts_check
  check (referrer_reward_cents >= 0 and referee_reward_cents >= 0
         and min_eligible_paid_cents > 0 and min_payout_cents > 0);
update public.referral_settings set referrer_reward_cents = 2000, min_eligible_paid_cents = 10000, min_payout_cents = 20000 where id;

-- ---------------------------------------------------------------------
-- 2) Remboursements de facture (montant final réellement payé)
-- ---------------------------------------------------------------------
alter table public.invoices
  add column if not exists refunded_cents integer not null default 0,
  add column if not exists refunded_at timestamptz;
alter table public.invoices add constraint invoices_refunded_cents_check
  check (refunded_cents >= 0 and (total_cents is null or refunded_cents <= total_cents));

create or replace function public.protect_invoice_amount_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (is_admin() or auth.role() = 'service_role') then
    new.status := old.status;
    new.total_cents := old.total_cents;
    new.refunded_cents := old.refunded_cents;
    new.refunded_at := old.refunded_at;
    new.paid_at := old.paid_at;
  end if;
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- 3) Référence anonyme des parrainages (« Client #4821 »)
-- ---------------------------------------------------------------------
alter table public.referrals add column if not exists public_no bigint generated by default as identity (start with 4801);
create unique index if not exists referrals_public_no_uidx on public.referrals (public_no);

-- ---------------------------------------------------------------------
-- 4) Tables du programme
-- ---------------------------------------------------------------------
create table if not exists public.referral_payout_requests (
  id uuid primary key default gen_random_uuid(),
  public_no bigint generated by default as identity (start with 1001) unique,
  referrer_client_id uuid not null references public.clients(id),
  amount_cents integer not null check (amount_cents > 0),
  status text not null default 'REQUESTED' check (status in ('REQUESTED', 'REVIEWING', 'APPROVED', 'PAID', 'REFUSED')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  approved_at timestamptz,
  paid_at timestamptz,
  refused_at timestamptz,
  refusal_reason text,
  admin_note text,
  payment_reference text,
  processed_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- Une seule demande active par parrain : deux demandes simultanées sont
-- impossibles même en cas de double clic / requêtes concurrentes.
create unique index if not exists referral_payout_one_active_uidx
  on public.referral_payout_requests (referrer_client_id)
  where status in ('REQUESTED', 'REVIEWING', 'APPROVED');

create table if not exists public.referral_rewards (
  id uuid primary key default gen_random_uuid(),
  referral_id uuid not null unique references public.referrals(id),
  referrer_client_id uuid not null references public.clients(id),
  referee_client_id uuid not null references public.clients(id),
  booking_id uuid references public.bookings(id),
  amount_cents integer not null check (amount_cents > 0),
  paid_amount_cents integer check (paid_amount_cents >= 0),
  status text not null default 'PENDING' check (status in ('PENDING', 'REVIEW', 'VALIDATED', 'REJECTED', 'CANCELLED')),
  status_code text not null default 'NO_BOOKING',
  status_reason text,
  review_flags text[] not null default '{}',
  validation_source text check (validation_source in ('auto_invoice', 'admin')),
  validated_at timestamptz,
  validated_by uuid,
  cancelled_at timestamptz,
  payout_id uuid references public.referral_payout_requests(id),
  clawback_alert boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (referrer_client_id <> referee_client_id),
  check (status <> 'VALIDATED' or (validated_at is not null and paid_amount_cents is not null and booking_id is not null)),
  check (payout_id is null or status = 'VALIDATED')
);
-- Une intervention ne peut générer qu'UNE prime validée.
create unique index if not exists referral_rewards_booking_validated_uidx
  on public.referral_rewards (booking_id) where status = 'VALIDATED';
create index if not exists referral_rewards_referrer_idx on public.referral_rewards (referrer_client_id, status);
create index if not exists referral_rewards_referee_idx on public.referral_rewards (referee_client_id);
create index if not exists referral_rewards_payout_idx on public.referral_rewards (payout_id);

create table if not exists public.referral_ledger (
  id uuid primary key default gen_random_uuid(),
  referrer_client_id uuid not null references public.clients(id),
  reward_id uuid references public.referral_rewards(id),
  payout_id uuid references public.referral_payout_requests(id),
  entry_type text not null check (entry_type in (
    'reward_pending', 'reward_validated', 'reward_cancelled', 'reward_clawback_alert',
    'payout_requested', 'payout_reviewing', 'payout_approved', 'payout_paid', 'payout_refused', 'payout_adjusted')),
  amount_cents integer not null default 0,
  detail jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now()
);
-- Idempotence financière : jamais deux validations / deux annulations de la
-- même prime, jamais deux fois la même étape pour une même demande.
create unique index if not exists referral_ledger_reward_once_uidx
  on public.referral_ledger (reward_id, entry_type)
  where reward_id is not null and entry_type in ('reward_pending', 'reward_validated', 'reward_cancelled', 'reward_clawback_alert');
create unique index if not exists referral_ledger_payout_once_uidx
  on public.referral_ledger (payout_id, entry_type)
  where payout_id is not null and entry_type in ('payout_requested', 'payout_reviewing', 'payout_approved', 'payout_paid', 'payout_refused');
create index if not exists referral_ledger_referrer_idx on public.referral_ledger (referrer_client_id, created_at desc);

create or replace function public.referral_ledger_immutable()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Le registre des parrainages est en ajout seul.';
end;
$$;
create trigger trg_referral_ledger_immutable
  before update or delete on public.referral_ledger
  for each row execute function public.referral_ledger_immutable();

create table if not exists public.referral_notifications (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id),
  kind text not null,
  title text not null,
  body text not null,
  dedupe_key text not null unique,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists referral_notifications_client_idx on public.referral_notifications (client_id, created_at desc);

-- RLS : lecture seule de ses propres demandes / notifications, tout le
-- reste réservé à l'administration ; aucune écriture directe.
alter table public.referral_rewards enable row level security;
alter table public.referral_payout_requests enable row level security;
alter table public.referral_ledger enable row level security;
alter table public.referral_notifications enable row level security;
create policy referral_rewards_admin_select on public.referral_rewards for select to authenticated using (is_admin());
create policy referral_ledger_admin_select on public.referral_ledger for select to authenticated using (is_admin());
create policy referral_payouts_select on public.referral_payout_requests for select to authenticated
  using (referrer_client_id = my_client_id() or is_admin());
create policy referral_notifications_select on public.referral_notifications for select to authenticated
  using (client_id = my_client_id() or is_admin());
revoke all on public.referral_rewards, public.referral_payout_requests, public.referral_ledger,
  public.referral_notifications, public.referral_settings, public.referrals, public.referral_codes,
  public.referral_events from anon, authenticated;
grant select on public.referral_rewards, public.referral_payout_requests, public.referral_ledger,
  public.referral_notifications, public.referral_settings, public.referrals, public.referral_codes,
  public.referral_events to authenticated;

-- ---------------------------------------------------------------------
-- 5) Fonctions internes
-- ---------------------------------------------------------------------
create or replace function public.referral_euros(p_cents integer)
returns text
language sql
immutable
as $$
  select case when p_cents % 100 = 0 then (p_cents / 100)::text || ' €'
              else replace(to_char(p_cents / 100.0, 'FM999999990D00'), '.', ',') || ' €' end;
$$;

create or replace function public.referral_notify_client(p_client uuid, p_kind text, p_title text, p_body text, p_dedupe text)
returns void
language sql
security definer
set search_path = public
as $$
  insert into referral_notifications (client_id, kind, title, body, dedupe_key)
  values (p_client, p_kind, p_title, p_body, p_dedupe)
  on conflict (dedupe_key) do nothing;
$$;

-- Montant final réellement payé d'une intervention : factures PAYÉES liées
-- (via le devis de la réservation), nettes des remboursements.
create or replace function public.referral_booking_payment(p_booking_id uuid, out paid_net_cents integer, out has_paid boolean, out has_invoice boolean, out foreign_client boolean)
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(case when i.status = 'PAID' then coalesce(i.total_cents, 0) - coalesce(i.refunded_cents, 0) else 0 end), 0)::int,
         coalesce(bool_or(i.status = 'PAID'), false),
         coalesce(bool_or(i.status <> 'CANCELLED'), false),
         coalesce(bool_or(i.client_id is not null and b.client_id is not null and i.client_id <> b.client_id
                          and not exists (select 1 from clients c where c.id = i.client_id and c.merged_into = b.client_id)), false)
  from invoices i
  join quotes q on q.id = i.quote_id
  join bookings b on b.id = q.booking_id
  where q.booking_id = p_booking_id;
$$;

create or replace function public.referral_balances(p_client uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'pending_cents', coalesce((select sum(amount_cents) from referral_rewards where referrer_client_id = p_client and status in ('PENDING', 'REVIEW')), 0),
    'available_cents', coalesce((select sum(amount_cents) from referral_rewards where referrer_client_id = p_client and status = 'VALIDATED' and payout_id is null and not clawback_alert), 0),
    'reserved_cents', coalesce((select sum(amount_cents) from referral_payout_requests where referrer_client_id = p_client and status in ('REQUESTED', 'REVIEWING', 'APPROVED')), 0),
    'paid_cents', coalesce((select sum(amount_cents) from referral_payout_requests where referrer_client_id = p_client and status = 'PAID'), 0),
    'clients_count', (select count(*) from referral_rewards where referrer_client_id = p_client),
    'validated_count', (select count(*) from referral_rewards where referrer_client_id = p_client and status = 'VALIDATED'),
    'pending_count', (select count(*) from referral_rewards where referrer_client_id = p_client and status in ('PENDING', 'REVIEW'))
  );
$$;

-- Libellé PUBLIC (vu par le parrain) d'une prime — jamais de détail privé.
create or replace function public.referral_public_label(p_status text, p_code text, p_min_cents integer)
returns text
language sql
immutable
as $$
  select case
    when p_status = 'VALIDATED' then 'Parrainage validé'
    when p_status = 'REVIEW' then 'Validation en cours'
    when p_status = 'PENDING' and p_code = 'BOOKED' then 'Intervention prévue'
    when p_status = 'PENDING' and p_code = 'AWAITING_PAYMENT' then 'Validation en cours'
    when p_status = 'PENDING' then 'En attente de réservation'
    when p_code = 'BELOW_MIN' then 'Facture inférieure à ' || public.referral_euros(p_min_cents) || ' — Non éligible'
    when p_code = 'EXISTING_CLIENT' then 'Client déjà connu de HAYEVA — Non éligible'
    when p_code = 'BOOKING_CANCELLED' then 'Rendez-vous annulé — Non éligible'
    when p_code = 'NO_SHOW' then 'Rendez-vous non honoré — Non éligible'
    when p_code = 'REFUNDED' then 'Prestation remboursée — Non éligible'
    else 'Non éligible'
  end;
$$;

-- Prime validée → crédit de bienvenue éventuel du filleul (programme
-- existant, wallet), statut du parrainage, notifications.
create or replace function public._referral_after_validation(p_reward_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  w referral_rewards%rowtype; s referral_settings%rowtype; v_bal jsonb; v_ree int;
begin
  select * into w from referral_rewards where id = p_reward_id;
  select * into s from referral_settings where id;
  v_ree := coalesce(s.referee_reward_cents, 0);
  if v_ree > 0 then
    insert into wallet_transactions (client_id, type, amount_cents, reason, referral_id, booking_id)
    values (w.referee_client_id, 'REFERRAL_REFEREE', v_ree, 'Avantage de bienvenue HAYEVA (parrainage)', w.referral_id, w.booking_id)
    on conflict (referral_id, type) where type in ('REFERRAL_REFERRER', 'REFERRAL_REFEREE') do nothing;
  end if;
  update referrals set status = 'VALIDATED', status_reason = null, qualifying_booking_id = w.booking_id,
         referrer_reward_cents = w.amount_cents, referee_reward_cents = v_ree, validated_at = coalesce(validated_at, now()), updated_at = now()
   where id = w.referral_id;
  insert into referral_events (referral_id, event, detail)
  values (w.referral_id, 'REWARD_VALIDATED', jsonb_build_object('reward_id', w.id, 'booking_id', w.booking_id, 'amount_cents', w.amount_cents, 'paid_amount_cents', w.paid_amount_cents, 'source', w.validation_source));
  perform referral_notify_client(w.referrer_client_id, 'reward_validated', '+' || referral_euros(w.amount_cents),
    'Votre parrainage a été validé. ' || referral_euros(w.amount_cents) || ' viennent d''être ajoutés à votre solde disponible.',
    'reward_validated:' || w.id);
  v_bal := referral_balances(w.referrer_client_id);
  if (v_bal->>'available_cents')::int >= s.min_payout_cents then
    perform referral_notify_client(w.referrer_client_id, 'payout_available', 'Versement disponible',
      'Votre solde disponible atteint ' || referral_euros(s.min_payout_cents) || '. Vous pouvez demander votre versement.',
      'payout_available:' || w.referrer_client_id || ':' || (select count(*) from referral_payout_requests where referrer_client_id = w.referrer_client_id));
  end if;
  perform admin_notify('payment', 'Parrainage validé', 'Prime de ' || referral_euros(w.amount_cents) || ' validée.', w.booking_id, 'referral-validated:' || w.id, false);
end;
$$;

-- Retire une prime validée d'une demande de versement non encore payée
-- (remboursement / annulation admin). La demande passe en vérification.
create or replace function public._referral_detach_from_payout(p_reward_id uuid, p_reason text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare w referral_rewards%rowtype; p referral_payout_requests%rowtype;
begin
  select * into w from referral_rewards where id = p_reward_id for update;
  if w.payout_id is null then return 'NONE'; end if;
  select * into p from referral_payout_requests where id = w.payout_id for update;
  if p.status = 'PAID' then return 'PAID'; end if;
  update referral_rewards set payout_id = null, updated_at = now() where id = w.id;
  if p.amount_cents - w.amount_cents <= 0 then
    update referral_payout_requests set status = 'REFUSED', refused_at = now(), refusal_reason = p_reason, updated_at = now() where id = p.id;
    insert into referral_ledger (referrer_client_id, payout_id, entry_type, amount_cents, detail)
    values (p.referrer_client_id, p.id, 'payout_refused', p.amount_cents, jsonb_build_object('reason', p_reason, 'auto', true))
    on conflict do nothing;
  else
    update referral_payout_requests set amount_cents = amount_cents - w.amount_cents,
           status = case when status = 'REQUESTED' then 'REVIEWING' else status end,
           admin_note = concat_ws(' | ', admin_note, p_reason), updated_at = now()
     where id = p.id;
    insert into referral_ledger (referrer_client_id, reward_id, payout_id, entry_type, amount_cents, detail)
    values (p.referrer_client_id, w.id, p.id, 'payout_adjusted', -w.amount_cents, jsonb_build_object('reason', p_reason));
  end if;
  perform admin_notify('payment', 'Demande de versement modifiée', 'Une prime a été retirée d''une demande de versement : ' || p_reason, null, 'referral-detach:' || w.id, true);
  return 'DETACHED';
end;
$$;

-- ---------------------------------------------------------------------
-- 6) Évaluation d'une prime — cœur du programme (idempotent)
-- ---------------------------------------------------------------------
create or replace function public.referral_evaluate_reward(p_reward_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  w referral_rewards%rowtype; r referrals%rowtype; s referral_settings%rowtype;
  ref_c clients%rowtype; ree_c clients%rowtype;
  v_ids uuid[]; v_flags text[]; v_status text; v_code text; v_reason text;
  v_booking uuid; v_paid int; v_pay record; bk record;
  v_awaiting uuid; v_below uuid; v_below_paid int; v_active int; v_cancelled int; v_noshow int;
  v_ins int; v_old_status text; v_old_code text;
begin
  select * into w from referral_rewards where id = p_reward_id for update;
  if not found then return 'NOT_FOUND'; end if;
  select * into s from referral_settings where id;
  select * into r from referrals where id = w.referral_id;
  v_old_status := w.status; v_old_code := w.status_code;

  -- (a) Prime déjà validée : seul un remboursement (facture payée devenue
  --     inférieure au seuil) peut encore la remettre en cause.
  if w.status = 'VALIDATED' then
    select * into v_pay from referral_booking_payment(w.booking_id);
    if v_pay.has_paid and v_pay.paid_net_cents < s.min_eligible_paid_cents then
      if w.payout_id is not null and _referral_detach_from_payout(w.id, 'Intervention remboursée') = 'PAID' then
        if not w.clawback_alert then
          update referral_rewards set clawback_alert = true,
                 status_reason = 'Récompense déjà versée — intervention remboursée — vérification requise', updated_at = now()
           where id = w.id;
          insert into referral_ledger (referrer_client_id, reward_id, payout_id, entry_type, amount_cents, detail)
          values (w.referrer_client_id, w.id, w.payout_id, 'reward_clawback_alert', 0, jsonb_build_object('paid_net_cents', v_pay.paid_net_cents))
          on conflict do nothing;
          perform admin_notify('payment', 'Parrainage — vérification requise',
            'Récompense déjà versée — intervention remboursée — vérification requise', w.booking_id, 'referral-clawback:' || w.id, true);
        end if;
        return 'CLAWBACK_ALERT';
      end if;
      update referral_rewards set status = 'CANCELLED', status_code = 'REFUNDED', status_reason = 'Intervention remboursée avant versement',
             cancelled_at = now(), paid_amount_cents = v_pay.paid_net_cents, updated_at = now()
       where id = w.id;
      insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail)
      values (w.referrer_client_id, w.id, 'reward_cancelled', -w.amount_cents, jsonb_build_object('reason', 'refund', 'paid_net_cents', v_pay.paid_net_cents))
      on conflict do nothing;
      update referrals set status = 'INELIGIBLE', status_reason = 'Intervention remboursée', updated_at = now() where id = w.referral_id;
      insert into referral_events (referral_id, event, detail) values (w.referral_id, 'REWARD_CANCELLED_REFUND', jsonb_build_object('reward_id', w.id));
      perform admin_notify('payment', 'Prime de parrainage annulée', 'Intervention remboursée avant versement : prime annulée.', w.booking_id, 'referral-refund:' || w.id, false);
      return 'CANCELLED_REFUND';
    end if;
    return 'VALIDATED';
  end if;

  -- (b) Décisions définitives : administration, remboursement.
  if w.status_code like 'ADMIN_%' or w.status_code = 'REFUNDED' then
    return 'FINAL_' || w.status;
  end if;
  if not s.is_enabled then
    return 'DISABLED';
  end if;

  select * into ref_c from clients where id = w.referrer_client_id;
  select * into ree_c from clients where id = w.referee_client_id;
  select array_agg(id) into v_ids from clients where id = w.referee_client_id or merged_into = w.referee_client_id;
  -- Drapeaux « collants » (posés par d'autres événements) conservés.
  v_flags := array(select f from unnest(w.review_flags) f where f in ('MULTI_CODE_ATTEMPT', 'ADMIN_FLAG'));

  -- (c) Auto-parrainage avéré : refus.
  if (ref_c.user_id is not null and ref_c.user_id = ree_c.user_id)
     or (nullif(lower(trim(ref_c.email)), '') is not null and lower(trim(ref_c.email)) = lower(trim(coalesce(ree_c.email, ''))))
     or (nullif(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), '') is not null
         and right(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), 9) = right(regexp_replace(coalesce(ree_c.phone, ''), '[^0-9]', '', 'g'), 9))
     or exists (select 1 from clients c where c.id = w.referee_client_id and c.merged_into = w.referrer_client_id)
  then
    v_status := 'REJECTED'; v_code := 'SELF_REFERRAL'; v_reason := 'Auto-parrainage (mêmes identifiants que le parrain)';
  -- (d) Client déjà existant avant le parrainage : refus.
  elsif exists (select 1 from bookings x where x.client_id = any(v_ids) and x.status = 'COMPLETED' and x.created_at < r.attributed_at - interval '5 minutes')
     or exists (select 1 from invoices i where i.client_id = any(v_ids) and i.status = 'PAID' and i.created_at < r.attributed_at)
  then
    v_status := 'REJECTED'; v_code := 'EXISTING_CLIENT'; v_reason := 'Client déjà existant avant le parrainage';
  else
    -- (e) Signaux à vérifier (jamais de prime automatique si signalé).
    if nullif(lower(regexp_replace(coalesce(ref_c.address, ''), '[^a-z0-9]', '', 'gi')), '') is not null
       and lower(regexp_replace(coalesce(ref_c.address, ''), '[^a-z0-9]', '', 'gi')) = lower(regexp_replace(coalesce(ree_c.address, ''), '[^a-z0-9]', '', 'gi')) then
      v_flags := array_append(v_flags, 'SAME_ADDRESS');
    end if;
    if exists (select 1 from bookings x where x.client_id = any(v_ids) and x.created_at < r.attributed_at - interval '1 hour' and x.status <> 'COMPLETED')
       or exists (select 1 from quotes q where q.client_id = any(v_ids) and q.created_at < r.attributed_at - interval '1 hour') then
      v_flags := array_append(v_flags, 'PRIOR_ACTIVITY');
    end if;
    if exists (select 1 from clients c2 join bookings x on x.client_id = c2.id
               where c2.id <> all(v_ids) and c2.merged_into is null and x.status = 'COMPLETED'
                 and ((nullif(lower(trim(ree_c.email)), '') is not null and lower(trim(c2.email)) = lower(trim(ree_c.email)))
                   or (nullif(regexp_replace(coalesce(ree_c.phone, ''), '[^0-9]', '', 'g'), '') is not null
                       and right(regexp_replace(coalesce(c2.phone, ''), '[^0-9]', '', 'g'), 9) = right(regexp_replace(coalesce(ree_c.phone, ''), '[^0-9]', '', 'g'), 9)))) then
      v_flags := array_append(v_flags, 'POSSIBLE_EXISTING_CLIENT');
    end if;
    if (select count(*) from bookings x where x.client_id = any(v_ids) and x.status in ('CANCELLED', 'NO_SHOW')) >= 3 then
      v_flags := array_append(v_flags, 'MANY_CANCELLATIONS');
    end if;
    if (select count(*) from referrals x where x.referrer_client_id = w.referrer_client_id
          and x.created_at between r.created_at - interval '24 hours' and r.created_at + interval '24 hours') >= 5 then
      v_flags := array_append(v_flags, 'REFERRER_BURST');
    end if;

    -- (f) Intervention qualifiante : terminée, prestation éligible,
    --     paiement confirmé >= seuil (net des remboursements).
    v_booking := null;
    for bk in
      select x.id, x.created_at from bookings x join services sv on sv.id = x.service_id
       where x.client_id = any(v_ids) and x.status = 'COMPLETED' and coalesce(sv.referral_eligible, false)
       order by x.date, x.start_time, x.created_at
    loop
      select * into v_pay from referral_booking_payment(bk.id);
      if v_pay.has_paid and v_pay.paid_net_cents >= s.min_eligible_paid_cents then
        v_booking := bk.id; v_paid := v_pay.paid_net_cents;
        if v_pay.foreign_client then v_flags := array_append(v_flags, 'PAYMENT_MISMATCH'); end if;
        if bk.created_at < r.attributed_at - interval '1 hour' then v_flags := array_append(v_flags, 'CODE_AFTER_BOOKING'); end if;
        exit;
      elsif not v_pay.has_paid and v_awaiting is null then
        v_awaiting := bk.id;
      elsif v_pay.has_paid and v_below is null then
        v_below := bk.id; v_below_paid := v_pay.paid_net_cents;
      end if;
    end loop;

    select count(*) filter (where x.status in ('PENDING', 'CONFIRMED', 'IN_PROGRESS')),
           count(*) filter (where x.status = 'CANCELLED'),
           count(*) filter (where x.status = 'NO_SHOW')
      into v_active, v_cancelled, v_noshow
      from bookings x where x.client_id = any(v_ids);

    if v_booking is not null then
      v_status := 'VALIDATED'; v_code := 'PAID_ELIGIBLE'; v_reason := null;
    elsif v_awaiting is not null then
      v_status := 'PENDING'; v_code := 'AWAITING_PAYMENT'; v_booking := v_awaiting;
      v_reason := 'Intervention terminée — paiement non confirmé : à valider par l''administrateur';
    elsif v_active > 0 then
      v_status := 'PENDING'; v_code := 'BOOKED'; v_reason := 'Intervention prévue';
      select x.id into v_booking from bookings x where x.client_id = any(v_ids) and x.status in ('PENDING', 'CONFIRMED', 'IN_PROGRESS') order by x.date, x.start_time limit 1;
    elsif v_below is not null then
      v_status := 'REJECTED'; v_code := 'BELOW_MIN'; v_booking := v_below; v_paid := v_below_paid;
      v_reason := 'Montant payé (' || referral_euros(v_below_paid) || ') inférieur au seuil de ' || referral_euros(s.min_eligible_paid_cents);
    elsif v_noshow > 0 and v_cancelled = 0 then
      v_status := 'CANCELLED'; v_code := 'NO_SHOW'; v_reason := 'Client absent';
    elsif v_cancelled > 0 or v_noshow > 0 then
      v_status := 'CANCELLED'; v_code := 'BOOKING_CANCELLED'; v_reason := 'Rendez-vous annulé';
    else
      v_status := 'PENDING'; v_code := 'NO_BOOKING'; v_reason := 'En attente de réservation';
    end if;

    -- Tout cas signalé passe « À vérifier » au lieu de créditer.
    if array_length(v_flags, 1) > 0 and v_status in ('PENDING', 'VALIDATED') then
      if v_status = 'VALIDATED' then v_code := 'FLAGGED_PAID'; v_reason := 'Paiement confirmé — à vérifier avant validation';
      end if;
      v_status := 'REVIEW';
    end if;
  end if;

  v_flags := array(select distinct f from unnest(v_flags) f order by 1);

  if v_status = 'VALIDATED' then
    -- Écriture du registre AVANT le changement de statut : l'index unique
    -- garantit un seul crédit, quelle que soit la concurrence.
    insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail)
    values (w.referrer_client_id, w.id, 'reward_validated', w.amount_cents,
            jsonb_build_object('booking_id', v_booking, 'paid_amount_cents', v_paid, 'source', 'auto_invoice'))
    on conflict do nothing;
    get diagnostics v_ins = row_count;
    if v_ins = 0 then return 'ALREADY_VALIDATED'; end if;
    update referral_rewards set status = 'VALIDATED', status_code = v_code, status_reason = null, review_flags = v_flags,
           booking_id = v_booking, paid_amount_cents = v_paid, validation_source = 'auto_invoice',
           validated_at = now(), updated_at = now()
     where id = w.id;
    perform _referral_after_validation(w.id);
    return 'VALIDATED';
  end if;

  if v_status is distinct from w.status or v_code is distinct from w.status_code or v_flags is distinct from w.review_flags
     or v_booking is distinct from w.booking_id or v_reason is distinct from w.status_reason then
    update referral_rewards set status = v_status, status_code = v_code, status_reason = v_reason, review_flags = v_flags,
           booking_id = v_booking, paid_amount_cents = case when v_code in ('BELOW_MIN', 'FLAGGED_PAID') then v_paid else paid_amount_cents end,
           cancelled_at = case when v_status = 'CANCELLED' then coalesce(cancelled_at, now()) else null end,
           updated_at = now()
     where id = w.id;
    insert into referral_events (referral_id, event, detail)
    values (w.referral_id, 'REWARD_' || v_status, jsonb_build_object('reward_id', w.id, 'code', v_code, 'from', v_old_status || '/' || v_old_code, 'flags', v_flags));
    update referrals set status = case when v_code in ('SELF_REFERRAL', 'EXISTING_CLIENT') then 'INELIGIBLE' else 'PENDING' end,
           status_reason = v_reason, updated_at = now()
     where id = w.referral_id and status <> 'VALIDATED';
    if v_status = 'REVIEW' and v_old_status <> 'REVIEW' then
      perform admin_notify('payment', 'Parrainage à vérifier', 'Un parrainage nécessite une vérification (' || array_to_string(v_flags, ', ') || ').',
        v_booking, 'referral-review:' || w.id || ':' || array_to_string(v_flags, ','), true);
    elsif v_code = 'AWAITING_PAYMENT' and v_old_code <> 'AWAITING_PAYMENT' then
      perform admin_notify('payment', 'Parrainage à valider', 'Intervention terminée d''un filleul : confirmez le paiement pour valider la prime.',
        v_booking, 'referral-awaiting:' || w.id || ':' || v_booking, false);
    end if;
  end if;
  return v_status || '/' || v_code;
end;
$$;

-- Réévalue toutes les primes d'un filleul (déclencheurs).
create or replace function public.referral_evaluate_for_client(p_client uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid;
begin
  if p_client is null then return; end if;
  for v_id in
    select rw.id from referral_rewards rw
     where rw.referee_client_id = p_client
        or rw.referee_client_id = (select merged_into from clients where id = p_client)
  loop
    perform referral_evaluate_reward(v_id);
  end loop;
end;
$$;

-- Compatibilité : ancienne entrée utilisée par admin_recheck_referral().
create or replace function public.process_referral_for_booking(p_booking_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_id uuid;
begin
  select client_id into v_client from bookings where id = p_booking_id;
  if v_client is null then return 'NO_CLIENT'; end if;
  select id into v_id from referral_rewards where referee_client_id = v_client;
  if v_id is null then return 'NO_REFERRAL'; end if;
  return referral_evaluate_reward(v_id);
end;
$$;

create or replace function public.referral_on_booking_completed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.status is distinct from OLD.status or NEW.client_id is distinct from OLD.client_id then
    begin
      perform referral_evaluate_for_client(NEW.client_id);
    exception when others then
      insert into referral_events (event, detail) values ('PROCESS_ERROR', jsonb_build_object('booking_id', NEW.id, 'error', SQLERRM));
    end;
  end if;
  return NEW;
end;
$$;
create or replace trigger trg_referral_on_booking_completed
  after update of status, client_id on public.bookings
  for each row execute function public.referral_on_booking_completed();

create or replace function public.referral_on_invoice_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid;
begin
  if tg_op = 'INSERT' or NEW.status is distinct from OLD.status or NEW.total_cents is distinct from OLD.total_cents
     or NEW.refunded_cents is distinct from OLD.refunded_cents or NEW.quote_id is distinct from OLD.quote_id then
    select b.client_id into v_client from quotes q join bookings b on b.id = q.booking_id where q.id = NEW.quote_id;
    if v_client is not null then
      begin
        perform referral_evaluate_for_client(v_client);
      exception when others then
        insert into referral_events (event, detail) values ('PROCESS_ERROR', jsonb_build_object('invoice_id', NEW.id, 'error', SQLERRM));
      end;
    end if;
  end if;
  return NEW;
end;
$$;
create or replace trigger trg_referral_on_invoice_status
  after insert or update of status, total_cents, refunded_cents, quote_id on public.invoices
  for each row execute function public.referral_on_invoice_status();

-- ---------------------------------------------------------------------
-- 7) Attribution du code (réservation, connexion, administration)
-- ---------------------------------------------------------------------
create or replace function public._attach_referral(p_referee uuid, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
  v_referrer uuid; ref_c clients%rowtype; ree_c clients%rowtype; v_existing referrals%rowtype; v_new uuid; v_reward uuid;
  s referral_settings%rowtype;
begin
  select * into s from referral_settings where id;
  if not s.is_enabled then return jsonb_build_object('ok', false, 'error', 'PROGRAMME_INACTIF'); end if;
  select client_id into v_referrer from referral_codes where code = v_code;
  if v_referrer is null then return jsonb_build_object('ok', false, 'error', 'CODE_INVALIDE'); end if;
  select * into ref_c from clients where id = v_referrer;
  select * into ree_c from clients where id = p_referee;
  if v_referrer = p_referee
     or (ref_c.user_id is not null and ref_c.user_id = ree_c.user_id)
     or (nullif(lower(trim(ref_c.email)), '') is not null and lower(trim(ref_c.email)) = lower(trim(ree_c.email)))
     or (nullif(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), '') is not null
         and right(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), 9) = right(regexp_replace(coalesce(ree_c.phone, ''), '[^0-9]', '', 'g'), 9))
  then
    insert into referral_events (event, detail) values ('SELF_REFERRAL_ATTEMPT', jsonb_build_object('referrer', v_referrer, 'referee', p_referee));
    return jsonb_build_object('ok', false, 'error', 'AUTO_PARRAINAGE');
  end if;

  select * into v_existing from referrals where referee_client_id = p_referee;
  if found then
    if v_existing.referrer_client_id = v_referrer then return jsonb_build_object('ok', true, 'already', true, 'status', v_existing.status); end if;
    -- Un autre code ne remplace JAMAIS le premier : tentative tracée et
    -- signalée à l'administration.
    insert into referral_events (referral_id, event, detail)
    values (v_existing.id, 'ATTACH_CONFLICT', jsonb_build_object('attempted_code', v_code));
    update referral_rewards set review_flags = array(select distinct f from unnest(review_flags || array['MULTI_CODE_ATTEMPT']) f), updated_at = now()
     where referral_id = v_existing.id and status in ('PENDING', 'REVIEW') and not ('MULTI_CODE_ATTEMPT' = any(review_flags));
    perform referral_evaluate_for_client(p_referee);
    return jsonb_build_object('ok', false, 'error', 'DEJA_PARRAINE');
  end if;
  if exists (select 1 from referrals where referee_client_id = v_referrer and referrer_client_id = p_referee) then
    return jsonb_build_object('ok', false, 'error', 'PARRAINAGE_CIRCULAIRE');
  end if;
  if exists (select 1 from bookings where client_id = p_referee and status = 'COMPLETED')
     or exists (select 1 from invoices where client_id = p_referee and status = 'PAID') then
    return jsonb_build_object('ok', false, 'error', 'CLIENT_DEJA_EXISTANT');
  end if;

  insert into referrals (referrer_client_id, referee_client_id, code_used, status_reason)
  values (v_referrer, p_referee, v_code, 'En attente de la première intervention éligible terminée')
  on conflict (referee_client_id) do nothing returning id into v_new;
  if v_new is null then return jsonb_build_object('ok', true, 'already', true); end if;
  insert into referral_events (referral_id, event, detail) values (v_new, 'ATTACHED', jsonb_build_object('code', v_code));

  if coalesce(s.referrer_reward_cents, 0) > 0 then
    insert into referral_rewards (referral_id, referrer_client_id, referee_client_id, amount_cents)
    values (v_new, v_referrer, p_referee, s.referrer_reward_cents)
    on conflict (referral_id) do nothing returning id into v_reward;
    if v_reward is not null then
      insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail)
      values (v_referrer, v_reward, 'reward_pending', s.referrer_reward_cents, jsonb_build_object('code', v_code))
      on conflict do nothing;
      perform referral_notify_client(v_referrer, 'new_referral', 'Nouveau parrainage',
        'Une nouvelle réservation a utilisé votre code HAYEVA. Votre prime est en attente de validation.', 'new_referral:' || v_reward);
      perform referral_evaluate_reward(v_reward);
    end if;
  end if;
  return jsonb_build_object('ok', true, 'already', false, 'status', 'PENDING');
end;
$$;

-- ---------------------------------------------------------------------
-- 8) Code personnel : générateur lisible + personnalisation
-- ---------------------------------------------------------------------
create or replace function public.generate_referral_code_for(p_client uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare v_base text; v text; i int := 0;
begin
  select left(regexp_replace(upper(translate(coalesce(first_name, ''),
           'àâäáãåçéèêëíìîïñóòôöõúùûüýÿÀÂÄÁÃÅÇÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝ',
           'aaaaaaceeeeiiiinooooouuuuyyAAAAAACEEEEIIIINOOOOOUUUUY')), '[^A-Z]', '', 'g'), 8)
    into v_base from clients where id = p_client;
  if coalesce(length(v_base), 0) >= 3 then
    loop
      i := i + 1;
      v := v_base || (10 + floor(random() * 90))::int::text;
      exit when not exists (select 1 from referral_codes where code = v);
      if i > 20 then exit; end if;
    end loop;
    if i <= 20 then return v; end if;
  end if;
  return generate_referral_code();
end;
$$;
revoke all on function public.generate_referral_code_for(uuid) from public, anon, authenticated;

create or replace function public.get_my_referral_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_code text;
begin
  v_client := public.ensure_my_client();
  select code into v_code from referral_codes where client_id = v_client;
  if v_code is null then
    loop
      begin
        insert into referral_codes (client_id, code) values (v_client, public.generate_referral_code_for(v_client)) returning code into v_code;
        exit;
      exception when unique_violation then
        select code into v_code from referral_codes where client_id = v_client;
        exit when v_code is not null;
      end;
    end loop;
  end if;
  return v_code;
end;
$$;

create or replace function public.set_my_referral_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_code text := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
begin
  v_client := public.ensure_my_client();
  if v_code !~ '^[A-Z0-9]{6,12}$' or v_code !~ '[A-Z]' then
    return jsonb_build_object('ok', false, 'error', 'FORMAT');
  end if;
  if exists (select 1 from referrals where referrer_client_id = v_client) then
    return jsonb_build_object('ok', false, 'error', 'CODE_DEJA_UTILISE');
  end if;
  if exists (select 1 from referral_codes where code = v_code and client_id <> v_client)
     or exists (select 1 from referrals where code_used = v_code) then
    return jsonb_build_object('ok', false, 'error', 'CODE_INDISPONIBLE');
  end if;
  begin
    insert into referral_codes (client_id, code) values (v_client, v_code)
    on conflict (client_id) do update set code = excluded.code;
  exception when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'CODE_INDISPONIBLE');
  end;
  return jsonb_build_object('ok', true, 'code', v_code);
end;
$$;

-- ---------------------------------------------------------------------
-- 9) Espace parrain
-- ---------------------------------------------------------------------
create or replace function public.get_referral_public_config()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'program_enabled', s.is_enabled,
    'ambassador_public_enabled', s.ambassador_public_enabled,
    'payouts_enabled', s.payouts_enabled,
    'reward_cents', s.referrer_reward_cents,
    'referee_reward_cents', s.referee_reward_cents,
    'min_eligible_paid_cents', s.min_eligible_paid_cents,
    'min_payout_cents', s.min_payout_cents)
  from referral_settings s where s.id;
$$;

create or replace function public.get_my_ambassador()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_had boolean; v_code text; s referral_settings%rowtype;
begin
  v_client := public.ensure_my_client();
  select exists (select 1 from referral_codes where client_id = v_client) into v_had;
  v_code := public.get_my_referral_code();
  select * into s from referral_settings where id;
  return jsonb_build_object(
    'code', v_code,
    'code_created', not v_had,
    'code_customizable', not exists (select 1 from referrals where referrer_client_id = v_client),
    'config', public.get_referral_public_config(),
    'balances', public.referral_balances(v_client),
    'has_active_payout', exists (select 1 from referral_payout_requests where referrer_client_id = v_client and status in ('REQUESTED', 'REVIEWING', 'APPROVED')),
    'referrals', coalesce((
      select jsonb_agg(jsonb_build_object(
               'ref', 'Client #' || rf.public_no,
               'status', rw.status,
               'label', public.referral_public_label(rw.status, rw.status_code, s.min_eligible_paid_cents),
               'amount_cents', rw.amount_cents,
               'created_at', rw.created_at,
               'validated_at', rw.validated_at) order by rw.created_at desc)
        from referral_rewards rw join referrals rf on rf.id = rw.referral_id
       where rw.referrer_client_id = v_client), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at) order by p.requested_at desc)
        from referral_payout_requests p where p.referrer_client_id = v_client), '[]'::jsonb),
    'notifications', coalesce((
      select jsonb_agg(jsonb_build_object('id', n.id, 'kind', n.kind, 'title', n.title, 'body', n.body, 'created_at', n.created_at, 'read', n.read_at is not null) order by n.created_at desc)
        from (select * from referral_notifications where client_id = v_client order by created_at desc limit 20) n), '[]'::jsonb),
    'wallet_balance_cents', coalesce((select balance_cents from wallet_balances where client_id = v_client), 0),
    'invited_by', (select jsonb_build_object('status', status) from referrals where referee_client_id = v_client)
  );
end;
$$;

create or replace function public.mark_my_referral_notifications_read()
returns void
language sql
security definer
set search_path = public
as $$
  update referral_notifications set read_at = now() where client_id = public.my_client_id() and read_at is null;
$$;

-- Demande de versement : transactionnelle. Le solde demandé est
-- immédiatement réservé (primes rattachées à la demande) et ne peut plus
-- faire l'objet d'une seconde demande.
create or replace function public.request_referral_payout()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; s referral_settings%rowtype; v_total int; v_id uuid; v_no bigint;
begin
  v_client := public.my_client_id();
  if auth.uid() is null or v_client is null then return jsonb_build_object('ok', false, 'error', 'AUTH_REQUIRED'); end if;
  select * into s from referral_settings where id;
  if not s.payouts_enabled then return jsonb_build_object('ok', false, 'error', 'VERSEMENTS_NON_OUVERTS'); end if;
  perform pg_advisory_xact_lock(hashtextextended('referral_payout:' || v_client::text, 0));
  if exists (select 1 from referral_payout_requests where referrer_client_id = v_client and status in ('REQUESTED', 'REVIEWING', 'APPROVED')) then
    return jsonb_build_object('ok', false, 'error', 'DEMANDE_EN_COURS');
  end if;
  perform 1 from referral_rewards where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert for update;
  select coalesce(sum(amount_cents), 0) into v_total from referral_rewards
   where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert;
  if v_total < s.min_payout_cents then
    return jsonb_build_object('ok', false, 'error', 'SEUIL_NON_ATTEINT', 'available_cents', v_total, 'min_payout_cents', s.min_payout_cents);
  end if;
  insert into referral_payout_requests (referrer_client_id, amount_cents) values (v_client, v_total) returning id, public_no into v_id, v_no;
  update referral_rewards set payout_id = v_id, updated_at = now()
   where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert;
  insert into referral_ledger (referrer_client_id, payout_id, entry_type, amount_cents, created_by)
  values (v_client, v_id, 'payout_requested', v_total, auth.uid());
  perform admin_notify('payment', 'Demande de versement parrainage', 'Demande n°' || v_no || ' — ' || referral_euros(v_total), null, 'referral-payout:' || v_id, true);
  return jsonb_build_object('ok', true, 'payout_no', v_no, 'amount_cents', v_total);
exception when unique_violation then
  return jsonb_build_object('ok', false, 'error', 'DEMANDE_EN_COURS');
end;
$$;

-- Ancienne lecture « fidélité » : plus aucun prénom de filleul exposé.
create or replace function public.get_my_loyalty()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; s referral_settings%rowtype; v_code text;
begin
  v_client := public.ensure_my_client();
  v_code := public.get_my_referral_code();
  select * into s from referral_settings where id;
  return jsonb_build_object(
    'code', v_code,
    'program_enabled', s.is_enabled,
    'referrer_reward_cents', s.referrer_reward_cents,
    'referee_reward_cents', s.referee_reward_cents,
    'balance_cents', coalesce((select balance_cents from wallet_balances where client_id = v_client), 0),
    'completed_interventions', (select count(*) from bookings where client_id = v_client and status = 'COMPLETED'),
    'validated_referrals', (select count(*) from referrals where referrer_client_id = v_client and status = 'VALIDATED'),
    'pending_referrals', (select count(*) from referrals where referrer_client_id = v_client and status = 'PENDING'),
    'invited_by', (select jsonb_build_object('status', status, 'reason', status_reason, 'reward_cents', coalesce(referee_reward_cents, s.referee_reward_cents))
                   from referrals where referee_client_id = v_client),
    'referrals', coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'first_name', 'Client #' || r.public_no,
                    'status', r.status, 'reason', r.status_reason, 'created_at', r.created_at, 'validated_at', r.validated_at,
                    'reward_cents', r.referrer_reward_cents) order by r.created_at desc)
                  from referrals r where r.referrer_client_id = v_client), '[]'::jsonb),
    'history', coalesce((select jsonb_agg(jsonb_build_object('created_at', t.created_at, 'type', t.type, 'amount_cents', t.amount_cents, 'reason', t.reason) order by t.created_at desc)
                  from (select * from wallet_transactions where client_id = v_client order by created_at desc limit 50) t), '[]'::jsonb)
  );
end;
$$;

-- ---------------------------------------------------------------------
-- 10) Administration
-- ---------------------------------------------------------------------
create or replace function public.admin_update_referral_settings(p jsonb)
returns referral_settings
language plpgsql
security definer
set search_path = public
as $$
declare r referral_settings%rowtype;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  update referral_settings set
    is_enabled = coalesce((p->>'is_enabled')::boolean, is_enabled),
    referrer_reward_cents = coalesce((p->>'referrer_reward_cents')::int, referrer_reward_cents),
    referee_reward_cents = coalesce((p->>'referee_reward_cents')::int, referee_reward_cents),
    require_paid_invoice = coalesce((p->>'require_paid_invoice')::boolean, require_paid_invoice),
    stacking_allowed = coalesce((p->>'stacking_allowed')::boolean, stacking_allowed),
    max_balance_cents = case when p ? 'max_balance_cents' then (p->>'max_balance_cents')::int else max_balance_cents end,
    credit_validity_days = case when p ? 'credit_validity_days' then (p->>'credit_validity_days')::int else credit_validity_days end,
    min_eligible_paid_cents = coalesce((p->>'min_eligible_paid_cents')::int, min_eligible_paid_cents),
    min_payout_cents = coalesce((p->>'min_payout_cents')::int, min_payout_cents),
    ambassador_public_enabled = coalesce((p->>'ambassador_public_enabled')::boolean, ambassador_public_enabled),
    payouts_enabled = coalesce((p->>'payouts_enabled')::boolean, payouts_enabled),
    updated_at = now(), updated_by = auth.uid()
  where id returning * into r;
  return r;
end;
$$;

create or replace function public.admin_referral_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  return jsonb_build_object(
    'settings', (select to_jsonb(s) - 'updated_by' from referral_settings s where s.id),
    'ambassadors_total', (select count(*) from referral_codes),
    'ambassadors_active', (select count(distinct referrer_client_id) from referral_rewards),
    'new_clients', (select count(*) from referral_rewards),
    'pending_count', (select count(*) from referral_rewards where status in ('PENDING', 'REVIEW')),
    'review_count', (select count(*) from referral_rewards where status = 'REVIEW' or (status = 'PENDING' and status_code = 'AWAITING_PAYMENT') or clawback_alert),
    'validated_count', (select count(*) from referral_rewards where status = 'VALIDATED'),
    'available_cents', coalesce((select sum(amount_cents) from referral_rewards where status = 'VALIDATED' and payout_id is null and not clawback_alert), 0),
    'payouts_requested', (select count(*) from referral_payout_requests where status in ('REQUESTED', 'REVIEWING', 'APPROVED')),
    'to_pay_cents', coalesce((select sum(amount_cents) from referral_payout_requests where status in ('REQUESTED', 'REVIEWING', 'APPROVED')), 0),
    'paid_cents', coalesce((select sum(amount_cents) from referral_payout_requests where status = 'PAID'), 0),
    'to_verify', coalesce((
      select jsonb_agg(x order by x->>'created_at') from (
        select jsonb_build_object('reward_id', rw.id, 'ref', 'Client #' || rf.public_no, 'status', rw.status, 'code', rw.status_code,
                 'reason', rw.status_reason, 'flags', rw.review_flags, 'clawback', rw.clawback_alert,
                 'referrer', trim(coalesce(a.first_name, '') || ' ' || coalesce(a.last_name, '')), 'referrer_client_id', rw.referrer_client_id,
                 'referee', trim(coalesce(f.first_name, '') || ' ' || coalesce(f.last_name, '')),
                 'booking_ref', bk.reference, 'booking_status', bk.status, 'paid_amount_cents', rw.paid_amount_cents, 'created_at', rw.created_at) x
          from referral_rewards rw join referrals rf on rf.id = rw.referral_id
          join clients a on a.id = rw.referrer_client_id join clients f on f.id = rw.referee_client_id
          left join bookings bk on bk.id = rw.booking_id
         where rw.status = 'REVIEW' or (rw.status = 'PENDING' and rw.status_code = 'AWAITING_PAYMENT') or rw.clawback_alert) t), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at, 'admin_note', p.admin_note, 'payment_reference', p.payment_reference,
               'referrer', trim(coalesce(a.first_name, '') || ' ' || coalesce(a.last_name, '')), 'referrer_client_id', p.referrer_client_id,
               'email', a.email, 'phone', a.phone) order by p.requested_at desc)
        from referral_payout_requests p join clients a on a.id = p.referrer_client_id), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_list_ambassadors(p_search text default null)
returns table(client_id uuid, name text, email text, code text, clients_count bigint, validated_count bigint,
              pending_cents bigint, available_cents bigint, reserved_cents bigint, paid_cents bigint, review_count bigint, last_activity timestamptz)
language plpgsql
stable
security definer
set search_path = public
as $$
declare q text := nullif(lower(trim(coalesce(p_search, ''))), '');
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  return query
  select c.id, trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, '')), c.email, rc.code,
         (select count(*) from referral_rewards w where w.referrer_client_id = c.id),
         (select count(*) from referral_rewards w where w.referrer_client_id = c.id and w.status = 'VALIDATED'),
         coalesce((select sum(w.amount_cents) from referral_rewards w where w.referrer_client_id = c.id and w.status in ('PENDING', 'REVIEW')), 0)::bigint,
         coalesce((select sum(w.amount_cents) from referral_rewards w where w.referrer_client_id = c.id and w.status = 'VALIDATED' and w.payout_id is null and not w.clawback_alert), 0)::bigint,
         coalesce((select sum(p.amount_cents) from referral_payout_requests p where p.referrer_client_id = c.id and p.status in ('REQUESTED', 'REVIEWING', 'APPROVED')), 0)::bigint,
         coalesce((select sum(p.amount_cents) from referral_payout_requests p where p.referrer_client_id = c.id and p.status = 'PAID'), 0)::bigint,
         (select count(*) from referral_rewards w where w.referrer_client_id = c.id and (w.status = 'REVIEW' or w.clawback_alert)),
         greatest(rc.created_at, (select max(w.updated_at) from referral_rewards w where w.referrer_client_id = c.id))
    from referral_codes rc join clients c on c.id = rc.client_id
   where q is null
      or lower(trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, ''))) like '%' || q || '%'
      or lower(rc.code) like '%' || q || '%'
      or lower(coalesce(c.email, '')) like '%' || q || '%'
      or exists (select 1 from referral_rewards w join referrals rf on rf.id = w.referral_id left join bookings b on b.id = w.booking_id
                  where w.referrer_client_id = c.id
                    and (lower(coalesce(b.reference, '')) like '%' || q || '%' or ('client #' || rf.public_no) like '%' || q || '%' or rf.public_no::text = q))
   order by 12 desc nulls last;
end;
$$;

create or replace function public.admin_ambassador_detail(p_client_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  return jsonb_build_object(
    'client', (select jsonb_build_object('id', c.id, 'name', trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, '')), 'email', c.email, 'phone', c.phone)
                 from clients c where c.id = p_client_id),
    'code', (select code from referral_codes where client_id = p_client_id),
    'balances', referral_balances(p_client_id),
    'rewards', coalesce((
      select jsonb_agg(jsonb_build_object('id', w.id, 'ref', 'Client #' || rf.public_no, 'status', w.status, 'code', w.status_code,
               'reason', w.status_reason, 'flags', w.review_flags, 'amount_cents', w.amount_cents, 'paid_amount_cents', w.paid_amount_cents,
               'referee', trim(coalesce(f.first_name, '') || ' ' || coalesce(f.last_name, '')), 'booking_ref', b.reference, 'booking_status', b.status,
               'validation_source', w.validation_source, 'validated_at', w.validated_at, 'payout_no', p.public_no, 'clawback', w.clawback_alert,
               'created_at', w.created_at) order by w.created_at desc)
        from referral_rewards w join referrals rf on rf.id = w.referral_id join clients f on f.id = w.referee_client_id
        left join bookings b on b.id = w.booking_id left join referral_payout_requests p on p.id = w.payout_id
       where w.referrer_client_id = p_client_id), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at, 'refusal_reason', p.refusal_reason, 'admin_note', p.admin_note,
               'payment_reference', p.payment_reference) order by p.requested_at desc)
        from referral_payout_requests p where p.referrer_client_id = p_client_id), '[]'::jsonb),
    'ledger', coalesce((
      select jsonb_agg(jsonb_build_object('type', l.entry_type, 'amount_cents', l.amount_cents, 'created_at', l.created_at, 'detail', l.detail) order by l.created_at desc)
        from (select * from referral_ledger where referrer_client_id = p_client_id order by created_at desc limit 100) l), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_recheck_referral_reward(p_reward_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  return referral_evaluate_reward(p_reward_id);
end;
$$;

-- Validation manuelle : uniquement lorsque l'intervention est TERMINÉE et
-- que l'administrateur confirme le montant réellement payé (>= seuil).
create or replace function public.admin_validate_referral_reward(p_reward_id uuid, p_paid_cents integer, p_note text default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare w referral_rewards%rowtype; s referral_settings%rowtype; v_booking uuid; v_ins int;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into s from referral_settings where id;
  select * into w from referral_rewards where id = p_reward_id for update;
  if not found then raise exception 'Prime introuvable.'; end if;
  if w.status = 'VALIDATED' then return 'ALREADY_VALIDATED'; end if;
  if w.status not in ('PENDING', 'REVIEW') then raise exception 'Cette prime n''est plus validable (statut %).', w.status; end if;
  if coalesce(p_paid_cents, 0) < s.min_eligible_paid_cents then
    raise exception 'Montant payé inférieur au seuil de % : aucune prime.', referral_euros(s.min_eligible_paid_cents);
  end if;
  if w.booking_id is not null and exists (select 1 from bookings where id = w.booking_id and status = 'COMPLETED') then
    v_booking := w.booking_id;
  else
    select x.id into v_booking from bookings x join services sv on sv.id = x.service_id
     where x.client_id in (select id from clients where id = w.referee_client_id or merged_into = w.referee_client_id)
       and x.status = 'COMPLETED' and coalesce(sv.referral_eligible, false)
     order by x.date, x.start_time limit 1;
  end if;
  if v_booking is null then raise exception 'Aucune intervention terminée pour ce filleul : validation impossible.'; end if;
  insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail, created_by)
  values (w.referrer_client_id, w.id, 'reward_validated', w.amount_cents,
          jsonb_build_object('booking_id', v_booking, 'paid_amount_cents', p_paid_cents, 'source', 'admin', 'note', p_note), auth.uid())
  on conflict do nothing;
  get diagnostics v_ins = row_count;
  if v_ins = 0 then return 'ALREADY_VALIDATED'; end if;
  update referral_rewards set status = 'VALIDATED', status_code = 'ADMIN_VALIDATED', status_reason = nullif(trim(coalesce(p_note, '')), ''),
         booking_id = v_booking, paid_amount_cents = p_paid_cents, validation_source = 'admin',
         validated_at = now(), validated_by = auth.uid(), updated_at = now()
   where id = w.id;
  perform _referral_after_validation(w.id);
  return 'VALIDATED';
end;
$$;

create or replace function public.admin_reject_referral_reward(p_reward_id uuid, p_reason text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare w referral_rewards%rowtype; v_reason text := coalesce(nullif(trim(p_reason), ''), 'Refusé par l''administration');
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into w from referral_rewards where id = p_reward_id for update;
  if not found then raise exception 'Prime introuvable.'; end if;
  if w.status = 'VALIDATED' then
    if w.payout_id is not null and _referral_detach_from_payout(w.id, v_reason) = 'PAID' then
      raise exception 'Prime déjà versée : régularisation à traiter manuellement.';
    end if;
    update referral_rewards set status = 'CANCELLED', status_code = 'ADMIN_CANCELLED', status_reason = v_reason,
           cancelled_at = now(), updated_at = now() where id = w.id;
    insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail, created_by)
    values (w.referrer_client_id, w.id, 'reward_cancelled', -w.amount_cents, jsonb_build_object('reason', v_reason, 'by', 'admin'), auth.uid())
    on conflict do nothing;
  else
    update referral_rewards set status = 'REJECTED', status_code = 'ADMIN_REJECTED', status_reason = v_reason, updated_at = now() where id = w.id;
  end if;
  update referrals set status = 'INELIGIBLE', status_reason = v_reason, updated_at = now() where id = w.referral_id;
  insert into referral_events (referral_id, event, detail) values (w.referral_id, 'ADMIN_REJECTED', jsonb_build_object('reason', v_reason, 'by', auth.uid()));
  return 'REJECTED';
end;
$$;

create or replace function public.admin_set_referral_payout_status(p_payout_id uuid, p_status text, p_note text default null, p_payment_reference text default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare p referral_payout_requests%rowtype; v_entry text;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into p from referral_payout_requests where id = p_payout_id for update;
  if not found then raise exception 'Demande introuvable.'; end if;
  if p.status = p_status then return p.status; end if;
  if not ((p.status = 'REQUESTED' and p_status in ('REVIEWING', 'APPROVED', 'REFUSED'))
       or (p.status = 'REVIEWING' and p_status in ('APPROVED', 'REFUSED'))
       or (p.status = 'APPROVED' and p_status in ('PAID', 'REFUSED'))) then
    raise exception 'Transition impossible : % → %.', p.status, p_status;
  end if;
  if p_status = 'PAID' and exists (select 1 from referral_rewards where payout_id = p.id and (status <> 'VALIDATED' or clawback_alert)) then
    raise exception 'Une prime de cette demande n''est plus valide : vérification requise.';
  end if;
  update referral_payout_requests set status = p_status,
         reviewed_at = case when p_status = 'REVIEWING' then now() else reviewed_at end,
         approved_at = case when p_status = 'APPROVED' then now() else approved_at end,
         paid_at = case when p_status = 'PAID' then now() else paid_at end,
         refused_at = case when p_status = 'REFUSED' then now() else refused_at end,
         refusal_reason = case when p_status = 'REFUSED' then nullif(trim(coalesce(p_note, '')), '') else refusal_reason end,
         admin_note = case when p_status <> 'REFUSED' and nullif(trim(coalesce(p_note, '')), '') is not null then concat_ws(' | ', admin_note, p_note) else admin_note end,
         payment_reference = coalesce(nullif(trim(coalesce(p_payment_reference, '')), ''), payment_reference),
         processed_by = auth.uid(), updated_at = now()
   where id = p.id;
  -- Refus : les primes redeviennent disponibles.
  if p_status = 'REFUSED' then
    update referral_rewards set payout_id = null, updated_at = now() where payout_id = p.id;
  end if;
  v_entry := 'payout_' || lower(p_status);
  insert into referral_ledger (referrer_client_id, payout_id, entry_type, amount_cents, detail, created_by)
  values (p.referrer_client_id, p.id, v_entry, p.amount_cents, jsonb_build_object('note', p_note, 'payment_reference', p_payment_reference), auth.uid())
  on conflict do nothing;
  perform referral_notify_client(p.referrer_client_id, 'payout_' || lower(p_status),
    case p_status when 'PAID' then 'Versement effectué' when 'APPROVED' then 'Versement approuvé' when 'REFUSED' then 'Demande de versement refusée' else 'Demande de versement en vérification' end,
    case p_status when 'PAID' then 'Votre versement de ' || referral_euros(p.amount_cents) || ' a été effectué.'
                  when 'APPROVED' then 'Votre demande de versement de ' || referral_euros(p.amount_cents) || ' a été approuvée.'
                  when 'REFUSED' then 'Votre demande de versement n''a pas pu être acceptée. Les montants concernés restent sur votre solde.'
                  else 'Votre demande de versement est en cours de vérification.' end,
    'payout_' || lower(p_status) || ':' || p.id);
  return p_status;
end;
$$;

create or replace function public.admin_mark_invoice_refunded(p_invoice_id uuid, p_refunded_cents integer)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare i invoices%rowtype;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into i from invoices where id = p_invoice_id for update;
  if not found then raise exception 'Facture introuvable.'; end if;
  if i.status <> 'PAID' then raise exception 'Seule une facture payée peut être remboursée.'; end if;
  if p_refunded_cents is null or p_refunded_cents < 0 or p_refunded_cents > coalesce(i.total_cents, 0) then
    raise exception 'Montant de remboursement invalide.';
  end if;
  update invoices set refunded_cents = p_refunded_cents, refunded_at = case when p_refunded_cents > 0 then now() else null end where id = i.id;
  return 'OK';
end;
$$;

-- ---------------------------------------------------------------------
-- 11) Analytics (aucune donnée personnelle : type + session anonyme + page)
-- ---------------------------------------------------------------------
alter policy "analytics_events: anyone can insert" on public.analytics_events
  with check (event_type = any (array['page_view', 'heartbeat', 'booking_started', 'booking_completed', 'contact_clicked', 'phone_clicked',
    'referral_page_view', 'referral_signup', 'referral_link_shared', 'referral_code_applied', 'referral_booking_completed',
    'referral_reward_pending', 'referral_reward_validated', 'referral_payout_requested']) and session_id is not null);

-- ---------------------------------------------------------------------
-- 12) Droits d'exécution
-- ---------------------------------------------------------------------
revoke all on function public.referral_euros(integer) from public, anon, authenticated;
revoke all on function public.referral_notify_client(uuid, text, text, text, text) from public, anon, authenticated;
revoke all on function public.referral_booking_payment(uuid) from public, anon, authenticated;
revoke all on function public.referral_balances(uuid) from public, anon, authenticated;
revoke all on function public.referral_public_label(text, text, integer) from public, anon, authenticated;
revoke all on function public._referral_after_validation(uuid) from public, anon, authenticated;
revoke all on function public._referral_detach_from_payout(uuid, text) from public, anon, authenticated;
revoke all on function public.referral_evaluate_reward(uuid) from public, anon, authenticated;
revoke all on function public.referral_evaluate_for_client(uuid) from public, anon, authenticated;
revoke all on function public.process_referral_for_booking(uuid) from public, anon, authenticated;
revoke all on function public.referral_on_booking_completed() from public, anon, authenticated;
revoke all on function public.referral_on_invoice_status() from public, anon, authenticated;
revoke all on function public._attach_referral(uuid, text) from public, anon, authenticated;
revoke all on function public.referral_ledger_immutable() from public, anon, authenticated;
revoke all on function public.protect_invoice_amount_fields() from public, anon, authenticated;

revoke all on function public.get_my_referral_code() from public, anon;
revoke all on function public.set_my_referral_code(text) from public, anon;
revoke all on function public.get_my_ambassador() from public, anon;
revoke all on function public.mark_my_referral_notifications_read() from public, anon;
revoke all on function public.request_referral_payout() from public, anon;
revoke all on function public.get_my_loyalty() from public, anon;
grant execute on function public.get_my_referral_code(), public.set_my_referral_code(text), public.get_my_ambassador(),
  public.mark_my_referral_notifications_read(), public.request_referral_payout(), public.get_my_loyalty() to authenticated;
grant execute on function public.get_referral_public_config() to anon, authenticated;

revoke all on function public.admin_update_referral_settings(jsonb) from public, anon;
revoke all on function public.admin_referral_dashboard() from public, anon;
revoke all on function public.admin_list_ambassadors(text) from public, anon;
revoke all on function public.admin_ambassador_detail(uuid) from public, anon;
revoke all on function public.admin_recheck_referral_reward(uuid) from public, anon;
revoke all on function public.admin_validate_referral_reward(uuid, integer, text) from public, anon;
revoke all on function public.admin_reject_referral_reward(uuid, text) from public, anon;
revoke all on function public.admin_set_referral_payout_status(uuid, text, text, text) from public, anon;
revoke all on function public.admin_mark_invoice_refunded(uuid, integer) from public, anon;
grant execute on function public.admin_update_referral_settings(jsonb), public.admin_referral_dashboard(), public.admin_list_ambassadors(text),
  public.admin_ambassador_detail(uuid), public.admin_recheck_referral_reward(uuid), public.admin_validate_referral_reward(uuid, integer, text),
  public.admin_reject_referral_reward(uuid, text), public.admin_set_referral_payout_status(uuid, text, text, text),
  public.admin_mark_invoice_refunded(uuid, integer) to authenticated;

-- ---------------------------------------------------------------------
-- 13) Reprise de l'existant : une prime EN ATTENTE pour chaque parrainage
--     encore en attente, puis évaluation (aucun crédit sans les conditions).
-- ---------------------------------------------------------------------
insert into public.referral_rewards (referral_id, referrer_client_id, referee_client_id, amount_cents)
select r.id, r.referrer_client_id, r.referee_client_id, (select referrer_reward_cents from public.referral_settings where id)
  from public.referrals r
 where r.status = 'PENDING' and (select referrer_reward_cents from public.referral_settings where id) > 0
on conflict (referral_id) do nothing;
insert into public.referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail)
select w.referrer_client_id, w.id, 'reward_pending', w.amount_cents, '{"backfill": true}'::jsonb from public.referral_rewards w
on conflict do nothing;
select public.referral_evaluate_reward(id) from public.referral_rewards;
