-- PARRAINAGE HAYEVA — distinction PARRAINS PARTICULIERS / APPORTEURS
-- D'AFFAIRES, création manuelle d'un parrain par l'administration.
--
-- Aucune nouvelle architecture : referral_codes devient le « profil » du
-- participant (type + statut), les primes, versements, registre, RLS et
-- l'anti-fraude de 0082 restent strictement identiques. Règle commerciale
-- inchangée : 20 € / prestation payée >= 100 € TTC / versement dès 200 €.
--
-- Apporteurs d'affaires : simple DEMANDE (formulaire) traitée par
-- l'administration ; un code « apporteur » n'est actif qu'après approbation.
-- Aucun seuil légal n'est programmé. Un seuil de SUIVI annuel peut être
-- saisi par l'administration (alerte interne uniquement, vide par défaut).

-- 1) Paramètres
alter table public.referral_settings
  add column if not exists business_program_public_enabled boolean not null default false,
  add column if not exists annual_tracking_threshold_cents integer;
alter table public.referral_settings add constraint referral_settings_tracking_check
  check (annual_tracking_threshold_cents is null or annual_tracking_threshold_cents > 0);

-- 2) Profil du participant (sur le code existant)
alter table public.referral_codes
  add column if not exists participant_type text not null default 'individual',
  add column if not exists status text not null default 'active',
  add column if not exists created_by uuid,
  add column if not exists updated_at timestamptz not null default now();
alter table public.referral_codes add constraint referral_codes_participant_type_check check (participant_type in ('individual', 'business'));
alter table public.referral_codes add constraint referral_codes_status_check check (status in ('active', 'suspended'));

-- Type du parrain figé sur chaque prime (prime de parrainage / commission).
alter table public.referral_rewards add column if not exists referrer_type text not null default 'individual';
alter table public.referral_rewards add constraint referral_rewards_referrer_type_check check (referrer_type in ('individual', 'business'));
create or replace function public.referral_rewards_set_type()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select coalesce(participant_type, 'individual') into new.referrer_type from referral_codes where client_id = new.referrer_client_id;
  new.referrer_type := coalesce(new.referrer_type, 'individual');
  return new;
end;
$$;
create or replace trigger trg_referral_rewards_set_type
  before insert on public.referral_rewards
  for each row execute function public.referral_rewards_set_type();

-- 3) Demandes « apporteur d'affaires »
create table if not exists public.referral_business_applications (
  id uuid primary key default gen_random_uuid(),
  public_no bigint generated by default as identity (start with 101) unique,
  client_id uuid references public.clients(id),
  legal_name text not null,
  contact_name text,
  email text not null,
  phone text,
  siren text,
  siret text,
  message text,
  status text not null default 'RECEIVED' check (status in ('RECEIVED', 'TO_VERIFY', 'APPROVED', 'REFUSED', 'SUSPENDED')),
  contact_consent_at timestamptz not null default now(),
  terms_version text,
  terms_accepted_at timestamptz,
  payment_details jsonb not null default '{}'::jsonb,
  admin_note text,
  reviewed_by uuid,
  reviewed_at timestamptz,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (siren is null or siren ~ '^[0-9]{9}$'),
  check (siret is null or siret ~ '^[0-9]{14}$')
);
create unique index if not exists referral_business_app_open_email_uidx
  on public.referral_business_applications (lower(email)) where status in ('RECEIVED', 'TO_VERIFY', 'APPROVED');
alter table public.referral_business_applications enable row level security;
create policy referral_business_app_admin_select on public.referral_business_applications for select to authenticated using (is_admin());
revoke all on public.referral_business_applications from anon, authenticated;
grant select on public.referral_business_applications to authenticated;

-- 4) Codes : seul un code ACTIF est reconnu
create or replace function public.get_referral_preview(p_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare s referral_settings%rowtype; v_ok boolean;
begin
  select * into s from referral_settings where id;
  select exists (select 1 from referral_codes where code = upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g')) and status = 'active') into v_ok;
  if not v_ok or not s.is_enabled then return jsonb_build_object('valid', false); end if;
  return jsonb_build_object('valid', true, 'referee_reward_cents', s.referee_reward_cents, 'referrer_reward_cents', s.referrer_reward_cents);
end;
$$;

create or replace function public._attach_referral(p_referee uuid, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
  v_referrer uuid; ref_c clients%rowtype; ree_c clients%rowtype; v_existing referrals%rowtype; v_new uuid; v_reward uuid;
  s referral_settings%rowtype;
begin
  select * into s from referral_settings where id;
  if not s.is_enabled then return jsonb_build_object('ok', false, 'error', 'PROGRAMME_INACTIF'); end if;
  select client_id into v_referrer from referral_codes where code = v_code and status = 'active';
  if v_referrer is null then return jsonb_build_object('ok', false, 'error', 'CODE_INVALIDE'); end if;
  select * into ref_c from clients where id = v_referrer;
  select * into ree_c from clients where id = p_referee;
  if v_referrer = p_referee
     or (ref_c.user_id is not null and ref_c.user_id = ree_c.user_id)
     or (nullif(lower(trim(ref_c.email)), '') is not null and lower(trim(ref_c.email)) = lower(trim(ree_c.email)))
     or (nullif(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), '') is not null
         and right(regexp_replace(coalesce(ref_c.phone, ''), '[^0-9]', '', 'g'), 9) = right(regexp_replace(coalesce(ree_c.phone, ''), '[^0-9]', '', 'g'), 9))
  then
    insert into referral_events (event, detail) values ('SELF_REFERRAL_ATTEMPT', jsonb_build_object('referrer', v_referrer, 'referee', p_referee));
    return jsonb_build_object('ok', false, 'error', 'AUTO_PARRAINAGE');
  end if;

  select * into v_existing from referrals where referee_client_id = p_referee;
  if found then
    if v_existing.referrer_client_id = v_referrer then return jsonb_build_object('ok', true, 'already', true, 'status', v_existing.status); end if;
    insert into referral_events (referral_id, event, detail)
    values (v_existing.id, 'ATTACH_CONFLICT', jsonb_build_object('attempted_code', v_code));
    update referral_rewards set review_flags = array(select distinct f from unnest(review_flags || array['MULTI_CODE_ATTEMPT']) f), updated_at = now()
     where referral_id = v_existing.id and status in ('PENDING', 'REVIEW') and not ('MULTI_CODE_ATTEMPT' = any(review_flags));
    perform referral_evaluate_for_client(p_referee);
    return jsonb_build_object('ok', false, 'error', 'DEJA_PARRAINE');
  end if;
  if exists (select 1 from referrals where referee_client_id = v_referrer and referrer_client_id = p_referee) then
    return jsonb_build_object('ok', false, 'error', 'PARRAINAGE_CIRCULAIRE');
  end if;
  if exists (select 1 from bookings where client_id = p_referee and status = 'COMPLETED')
     or exists (select 1 from invoices where client_id = p_referee and status = 'PAID') then
    return jsonb_build_object('ok', false, 'error', 'CLIENT_DEJA_EXISTANT');
  end if;

  insert into referrals (referrer_client_id, referee_client_id, code_used, status_reason)
  values (v_referrer, p_referee, v_code, 'En attente de la première intervention éligible terminée')
  on conflict (referee_client_id) do nothing returning id into v_new;
  if v_new is null then return jsonb_build_object('ok', true, 'already', true); end if;
  insert into referral_events (referral_id, event, detail) values (v_new, 'ATTACHED', jsonb_build_object('code', v_code));

  if coalesce(s.referrer_reward_cents, 0) > 0 then
    insert into referral_rewards (referral_id, referrer_client_id, referee_client_id, amount_cents)
    values (v_new, v_referrer, p_referee, s.referrer_reward_cents)
    on conflict (referral_id) do nothing returning id into v_reward;
    if v_reward is not null then
      insert into referral_ledger (referrer_client_id, reward_id, entry_type, amount_cents, detail)
      values (v_referrer, v_reward, 'reward_pending', s.referrer_reward_cents, jsonb_build_object('code', v_code))
      on conflict do nothing;
      perform referral_notify_client(v_referrer, 'new_referral', 'Nouveau parrainage',
        'Une nouvelle réservation a utilisé votre code HAYEVA. Votre prime est en attente de validation.', 'new_referral:' || v_reward);
      perform referral_evaluate_reward(v_reward);
    end if;
  end if;
  return jsonb_build_object('ok', true, 'already', false, 'status', 'PENDING');
end;
$$;

-- Demande de versement : refusée pour un compte suspendu.
create or replace function public.request_referral_payout()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; s referral_settings%rowtype; v_total int; v_id uuid; v_no bigint;
begin
  v_client := public.my_client_id();
  if auth.uid() is null or v_client is null then return jsonb_build_object('ok', false, 'error', 'AUTH_REQUIRED'); end if;
  select * into s from referral_settings where id;
  if not s.payouts_enabled then return jsonb_build_object('ok', false, 'error', 'VERSEMENTS_NON_OUVERTS'); end if;
  if exists (select 1 from referral_codes where client_id = v_client and status = 'suspended') then
    return jsonb_build_object('ok', false, 'error', 'COMPTE_SUSPENDU');
  end if;
  perform pg_advisory_xact_lock(hashtextextended('referral_payout:' || v_client::text, 0));
  if exists (select 1 from referral_payout_requests where referrer_client_id = v_client and status in ('REQUESTED', 'REVIEWING', 'APPROVED')) then
    return jsonb_build_object('ok', false, 'error', 'DEMANDE_EN_COURS');
  end if;
  perform 1 from referral_rewards where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert for update;
  select coalesce(sum(amount_cents), 0) into v_total from referral_rewards
   where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert;
  if v_total < s.min_payout_cents then
    return jsonb_build_object('ok', false, 'error', 'SEUIL_NON_ATTEINT', 'available_cents', v_total, 'min_payout_cents', s.min_payout_cents);
  end if;
  insert into referral_payout_requests (referrer_client_id, amount_cents) values (v_client, v_total) returning id, public_no into v_id, v_no;
  update referral_rewards set payout_id = v_id, updated_at = now()
   where referrer_client_id = v_client and status = 'VALIDATED' and payout_id is null and not clawback_alert;
  insert into referral_ledger (referrer_client_id, payout_id, entry_type, amount_cents, created_by)
  values (v_client, v_id, 'payout_requested', v_total, auth.uid());
  perform admin_notify('payment', 'Demande de versement parrainage', 'Demande n°' || v_no || ' — ' || referral_euros(v_total), null, 'referral-payout:' || v_id, true);
  return jsonb_build_object('ok', true, 'payout_no', v_no, 'amount_cents', v_total);
exception when unique_violation then
  return jsonb_build_object('ok', false, 'error', 'DEMANDE_EN_COURS');
end;
$$;

-- 5) Configuration publique et espace parrain : type + statut
create or replace function public.get_referral_public_config()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'program_enabled', s.is_enabled,
    'ambassador_public_enabled', s.ambassador_public_enabled,
    'business_program_public_enabled', s.business_program_public_enabled,
    'payouts_enabled', s.payouts_enabled,
    'reward_cents', s.referrer_reward_cents,
    'referee_reward_cents', s.referee_reward_cents,
    'min_eligible_paid_cents', s.min_eligible_paid_cents,
    'min_payout_cents', s.min_payout_cents)
  from referral_settings s where s.id;
$$;

create or replace function public.get_my_ambassador()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_had boolean; v_code text; s referral_settings%rowtype; rc referral_codes%rowtype;
begin
  v_client := public.ensure_my_client();
  select exists (select 1 from referral_codes where client_id = v_client) into v_had;
  v_code := public.get_my_referral_code();
  select * into rc from referral_codes where client_id = v_client;
  select * into s from referral_settings where id;
  return jsonb_build_object(
    'code', v_code,
    'code_created', not v_had,
    'code_customizable', not exists (select 1 from referrals where referrer_client_id = v_client) and rc.created_by is null,
    'participant_type', rc.participant_type,
    'participant_status', rc.status,
    'config', public.get_referral_public_config(),
    'balances', public.referral_balances(v_client),
    'has_active_payout', exists (select 1 from referral_payout_requests where referrer_client_id = v_client and status in ('REQUESTED', 'REVIEWING', 'APPROVED')),
    'referrals', coalesce((
      select jsonb_agg(jsonb_build_object(
               'ref', 'Client #' || rf.public_no,
               'status', rw.status,
               'label', public.referral_public_label(rw.status, rw.status_code, s.min_eligible_paid_cents),
               'amount_cents', rw.amount_cents,
               'created_at', rw.created_at,
               'validated_at', rw.validated_at) order by rw.created_at desc)
        from referral_rewards rw join referrals rf on rf.id = rw.referral_id
       where rw.referrer_client_id = v_client), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at) order by p.requested_at desc)
        from referral_payout_requests p where p.referrer_client_id = v_client), '[]'::jsonb),
    'notifications', coalesce((
      select jsonb_agg(jsonb_build_object('id', n.id, 'kind', n.kind, 'title', n.title, 'body', n.body, 'created_at', n.created_at, 'read', n.read_at is not null) order by n.created_at desc)
        from (select * from referral_notifications where client_id = v_client order by created_at desc limit 20) n), '[]'::jsonb),
    'wallet_balance_cents', coalesce((select balance_cents from wallet_balances where client_id = v_client), 0),
    'invited_by', (select jsonb_build_object('status', status) from referrals where referee_client_id = v_client)
  );
end;
$$;

-- 6) Formulaire public « apporteur d'affaires » (simple demande)
create or replace function public.submit_business_referrer_application(
  p_legal_name text, p_contact_name text, p_email text, p_phone text, p_siren_siret text, p_message text, p_contact_consent boolean)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s referral_settings%rowtype;
  v_email text := lower(trim(coalesce(p_email, '')));
  v_num text := regexp_replace(coalesce(p_siren_siret, ''), '\s', '', 'g');
  v_id uuid; v_no bigint;
begin
  select * into s from referral_settings where id;
  if not s.business_program_public_enabled then return jsonb_build_object('ok', false, 'error', 'INDISPONIBLE'); end if;
  if not coalesce(p_contact_consent, false) then return jsonb_build_object('ok', false, 'error', 'CONSENTEMENT'); end if;
  if length(trim(coalesce(p_legal_name, ''))) < 2 or length(p_legal_name) > 160 then return jsonb_build_object('ok', false, 'error', 'NOM'); end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 200 then return jsonb_build_object('ok', false, 'error', 'EMAIL'); end if;
  if v_num <> '' and v_num !~ '^([0-9]{9}|[0-9]{14})$' then return jsonb_build_object('ok', false, 'error', 'SIREN'); end if;
  if length(coalesce(p_message, '')) > 2000 or length(coalesce(p_phone, '')) > 30 or length(coalesce(p_contact_name, '')) > 160 then
    return jsonb_build_object('ok', false, 'error', 'TROP_LONG');
  end if;
  if (select count(*) from referral_business_applications where created_at > now() - interval '1 hour') >= 20 then
    return jsonb_build_object('ok', false, 'error', 'TROP_DE_DEMANDES');
  end if;
  begin
    insert into referral_business_applications (legal_name, contact_name, email, phone, siren, siret, message)
    values (trim(p_legal_name), nullif(trim(coalesce(p_contact_name, '')), ''), v_email, nullif(trim(coalesce(p_phone, '')), ''),
            case when length(v_num) = 9 then v_num when length(v_num) = 14 then left(v_num, 9) end,
            case when length(v_num) = 14 then v_num end, nullif(trim(coalesce(p_message, '')), ''))
    returning id, public_no into v_id, v_no;
  exception when unique_violation then
    -- Demande déjà en cours pour cet e-mail : réponse identique (aucune fuite).
    return jsonb_build_object('ok', true);
  end;
  perform admin_notify('new_request', 'Demande apporteur d''affaires', 'Demande n°' || v_no || ' — ' || trim(p_legal_name), null, 'business-app:' || v_id, true);
  return jsonb_build_object('ok', true);
end;
$$;

-- 7) Administration
create or replace function public.admin_update_referral_settings(p jsonb)
returns referral_settings
language plpgsql
security definer
set search_path = public
as $$
declare r referral_settings%rowtype;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  update referral_settings set
    is_enabled = coalesce((p->>'is_enabled')::boolean, is_enabled),
    referrer_reward_cents = coalesce((p->>'referrer_reward_cents')::int, referrer_reward_cents),
    referee_reward_cents = coalesce((p->>'referee_reward_cents')::int, referee_reward_cents),
    require_paid_invoice = coalesce((p->>'require_paid_invoice')::boolean, require_paid_invoice),
    stacking_allowed = coalesce((p->>'stacking_allowed')::boolean, stacking_allowed),
    max_balance_cents = case when p ? 'max_balance_cents' then (p->>'max_balance_cents')::int else max_balance_cents end,
    credit_validity_days = case when p ? 'credit_validity_days' then (p->>'credit_validity_days')::int else credit_validity_days end,
    min_eligible_paid_cents = coalesce((p->>'min_eligible_paid_cents')::int, min_eligible_paid_cents),
    min_payout_cents = coalesce((p->>'min_payout_cents')::int, min_payout_cents),
    ambassador_public_enabled = coalesce((p->>'ambassador_public_enabled')::boolean, ambassador_public_enabled),
    business_program_public_enabled = coalesce((p->>'business_program_public_enabled')::boolean, business_program_public_enabled),
    payouts_enabled = coalesce((p->>'payouts_enabled')::boolean, payouts_enabled),
    annual_tracking_threshold_cents = case when p ? 'annual_tracking_threshold_cents' then nullif((p->>'annual_tracking_threshold_cents')::int, 0) else annual_tracking_threshold_cents end,
    updated_at = now(), updated_by = auth.uid()
  where id returning * into r;
  return r;
end;
$$;

-- Suggestion de code lisible : PRÉNOM + 2 chiffres (ex. CLEMENT01).
create or replace function public.admin_suggest_referral_code(p_first_name text)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare v_base text; v text; i int;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  v_base := left(regexp_replace(upper(translate(coalesce(p_first_name, ''),
           'àâäáãåçéèêëíìîïñóòôöõúùûüýÿÀÂÄÁÃÅÇÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝ',
           'aaaaaaceeeeiiiinooooouuuuyyAAAAAACEEEEIIIINOOOOOUUUUY')), '[^A-Z]', '', 'g'), 10);
  if length(v_base) < 2 then v_base := 'HAYEVA'; end if;
  for i in 1..99 loop
    v := v_base || lpad(i::text, 2, '0');
    if length(v) >= 6 and not exists (select 1 from referral_codes where code = v) and not exists (select 1 from referrals where code_used = v) then
      return v;
    end if;
  end loop;
  return generate_referral_code();
end;
$$;

-- Création manuelle d'un parrain (administrateurs uniquement).
create or replace function public.admin_create_referrer(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_first text := nullif(trim(coalesce(p->>'first_name', '')), '');
  v_last text := nullif(trim(coalesce(p->>'last_name', '')), '');
  v_email text := lower(trim(coalesce(p->>'email', '')));
  v_phone text := nullif(trim(coalesce(p->>'phone', '')), '');
  v_code text := upper(regexp_replace(coalesce(p->>'code', ''), '\s', '', 'g'));
  v_type text := coalesce(nullif(p->>'participant_type', ''), 'individual');
  v_client uuid; v_existing text;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  if v_first is null then return jsonb_build_object('ok', false, 'error', 'PRENOM'); end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then return jsonb_build_object('ok', false, 'error', 'EMAIL'); end if;
  if v_code !~ '^[A-Z0-9]{6,12}$' or v_code !~ '[A-Z]' then return jsonb_build_object('ok', false, 'error', 'FORMAT'); end if;
  if v_type not in ('individual', 'business') then return jsonb_build_object('ok', false, 'error', 'TYPE'); end if;
  if exists (select 1 from referral_codes where code = v_code) or exists (select 1 from referrals where code_used = v_code) then
    return jsonb_build_object('ok', false, 'error', 'CODE_EXISTANT');
  end if;
  v_client := find_or_create_client(null, v_email, v_phone, v_first, v_last, null);
  select code into v_existing from referral_codes where client_id = v_client;
  if v_existing is not null then
    return jsonb_build_object('ok', false, 'error', 'DEJA_PARRAIN', 'code', v_existing, 'client_id', v_client);
  end if;
  begin
    insert into referral_codes (client_id, code, participant_type, status, created_by)
    values (v_client, v_code, v_type, 'active', auth.uid());
  exception when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'CODE_EXISTANT');
  end;
  return jsonb_build_object('ok', true, 'client_id', v_client, 'code', v_code, 'link', 'https://hayeva.fr/rdv?ref=' || v_code);
end;
$$;

-- Désactivation / réactivation d'un parrain. Les primes en attente d'un
-- parrain suspendu passent « À vérifier » (jamais validées automatiquement).
create or replace function public.admin_set_referrer_status(p_client_id uuid, p_status text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  if p_status not in ('active', 'suspended') then raise exception 'Statut invalide.'; end if;
  update referral_codes set status = p_status, updated_at = now() where client_id = p_client_id;
  if not found then raise exception 'Parrain introuvable.'; end if;
  if p_status = 'suspended' then
    update referral_rewards set review_flags = array(select distinct f from unnest(review_flags || array['ADMIN_FLAG']) f), updated_at = now()
     where referrer_client_id = p_client_id and status in ('PENDING', 'REVIEW') and not ('ADMIN_FLAG' = any(review_flags));
  else
    update referral_rewards set review_flags = array_remove(review_flags, 'ADMIN_FLAG'), updated_at = now()
     where referrer_client_id = p_client_id and status in ('PENDING', 'REVIEW') and 'ADMIN_FLAG' = any(review_flags);
  end if;
  for v_id in select id from referral_rewards where referrer_client_id = p_client_id and status in ('PENDING', 'REVIEW') loop
    perform referral_evaluate_reward(v_id);
  end loop;
  return p_status;
end;
$$;

-- Traitement d'une demande apporteur d'affaires. Approbation = création ou
-- passage du code en « apporteur » actif ; refus/suspension = code suspendu.
create or replace function public.admin_set_business_application_status(p_id uuid, p_status text, p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare a referral_business_applications%rowtype; v_client uuid; v_first text; v_last text;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  if p_status not in ('RECEIVED', 'TO_VERIFY', 'APPROVED', 'REFUSED', 'SUSPENDED') then raise exception 'Statut invalide.'; end if;
  select * into a from referral_business_applications where id = p_id for update;
  if not found then raise exception 'Demande introuvable.'; end if;
  v_client := a.client_id;
  if p_status = 'APPROVED' then
    v_first := split_part(coalesce(a.contact_name, a.legal_name), ' ', 1);
    v_last := nullif(trim(substring(coalesce(a.contact_name, a.legal_name) from length(v_first) + 1)), '');
    if v_client is null then v_client := find_or_create_client(null, a.email, a.phone, v_first, v_last, null); end if;
    if exists (select 1 from referral_codes where client_id = v_client) then
      update referral_codes set participant_type = 'business', status = 'active', updated_at = now() where client_id = v_client;
    else
      insert into referral_codes (client_id, code, participant_type, status, created_by)
      values (v_client, generate_referral_code_for(v_client), 'business', 'active', auth.uid());
    end if;
  elsif p_status in ('REFUSED', 'SUSPENDED') and v_client is not null then
    perform admin_set_referrer_status(v_client, 'suspended');
  end if;
  update referral_business_applications set status = p_status, client_id = v_client,
         admin_note = case when nullif(trim(coalesce(p_note, '')), '') is not null then concat_ws(' | ', admin_note, p_note) else admin_note end,
         reviewed_by = auth.uid(), reviewed_at = now(),
         approved_at = case when p_status = 'APPROVED' then coalesce(approved_at, now()) else approved_at end,
         updated_at = now()
   where id = a.id;
  return jsonb_build_object('ok', true, 'client_id', v_client, 'code', (select code from referral_codes where client_id = v_client));
end;
$$;

-- Liste des participants (parrains particuliers / apporteurs d'affaires).
create or replace function public.admin_list_referrers(p_search text default null, p_filter text default 'all')
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare q text := nullif(lower(trim(coalesce(p_search, ''))), ''); s referral_settings%rowtype; v_year_start timestamptz;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into s from referral_settings where id;
  v_year_start := date_trunc('year', now() at time zone 'Europe/Paris') at time zone 'Europe/Paris';
  return coalesce((
    select jsonb_agg(x order by (x->>'last_activity') desc nulls last) from (
      select jsonb_build_object(
        'client_id', c.id, 'name', trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, '')), 'email', c.email,
        'code', rc.code, 'participant_type', rc.participant_type, 'status', rc.status,
        'clients_count', b.clients_count, 'validated_count', b.validated_count,
        'pending_cents', b.pending_cents, 'available_cents', b.available_cents, 'reserved_cents', b.reserved_cents, 'paid_cents', b.paid_cents,
        'paid_year_cents', y.paid_year_cents, 'review_count', rv.review_count,
        'alerts', to_jsonb(array_remove(array[
            case when rc.status = 'suspended' then 'SUSPENDU' end,
            case when rv.review_count > 0 then 'A_VERIFIER' end,
            case when s.annual_tracking_threshold_cents is not null and y.paid_year_cents >= s.annual_tracking_threshold_cents then 'SEUIL_SUIVI_ANNUEL' end,
            case when rc.participant_type = 'business' and not exists (select 1 from referral_business_applications ba where ba.client_id = c.id and ba.status = 'APPROVED' and (ba.siren is not null or ba.siret is not null)) then 'INFOS_ADMINISTRATIVES' end
          ], null)),
        'last_activity', greatest(rc.created_at, rc.updated_at, (select max(w.updated_at) from referral_rewards w where w.referrer_client_id = c.id))) x
      from referral_codes rc join clients c on c.id = rc.client_id
      cross join lateral (select
          (select count(*) from referral_rewards w where w.referrer_client_id = c.id) clients_count,
          (select count(*) from referral_rewards w where w.referrer_client_id = c.id and w.status = 'VALIDATED') validated_count,
          coalesce((select sum(w.amount_cents) from referral_rewards w where w.referrer_client_id = c.id and w.status in ('PENDING', 'REVIEW')), 0) pending_cents,
          coalesce((select sum(w.amount_cents) from referral_rewards w where w.referrer_client_id = c.id and w.status = 'VALIDATED' and w.payout_id is null and not w.clawback_alert), 0) available_cents,
          coalesce((select sum(p.amount_cents) from referral_payout_requests p where p.referrer_client_id = c.id and p.status in ('REQUESTED', 'REVIEWING', 'APPROVED')), 0) reserved_cents,
          coalesce((select sum(p.amount_cents) from referral_payout_requests p where p.referrer_client_id = c.id and p.status = 'PAID'), 0) paid_cents) b
      cross join lateral (select coalesce((select sum(p.amount_cents) from referral_payout_requests p where p.referrer_client_id = c.id and p.status = 'PAID' and p.paid_at >= v_year_start), 0) paid_year_cents) y
      cross join lateral (select (select count(*) from referral_rewards w where w.referrer_client_id = c.id and (w.status = 'REVIEW' or w.clawback_alert)) review_count) rv
      where (q is null
          or lower(trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, ''))) like '%' || q || '%'
          or lower(rc.code) like '%' || q || '%'
          or lower(coalesce(c.email, '')) like '%' || q || '%'
          or exists (select 1 from referral_rewards w join referrals rf on rf.id = w.referral_id left join bookings bk on bk.id = w.booking_id
                      where w.referrer_client_id = c.id
                        and (lower(coalesce(bk.reference, '')) like '%' || q || '%' or ('client #' || rf.public_no) like '%' || q || '%' or rf.public_no::text = q)))
        and (coalesce(p_filter, 'all') = 'all'
          or (p_filter = 'individual' and rc.participant_type = 'individual')
          or (p_filter = 'business' and rc.participant_type = 'business')
          or (p_filter = 'review' and rv.review_count > 0)
          or (p_filter = 'suspended' and rc.status = 'suspended')
          or (p_filter = 'available' and b.available_cents > 0)
          or (p_filter = 'reserved' and b.reserved_cents > 0))
    ) t), '[]'::jsonb);
end;
$$;

create or replace function public.admin_ambassador_detail(p_client_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare rc referral_codes%rowtype; v_year_start timestamptz;
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  select * into rc from referral_codes where client_id = p_client_id;
  v_year_start := date_trunc('year', now() at time zone 'Europe/Paris') at time zone 'Europe/Paris';
  return jsonb_build_object(
    'client', (select jsonb_build_object('id', c.id, 'name', trim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, '')), 'email', c.email, 'phone', c.phone)
                 from clients c where c.id = p_client_id),
    'code', rc.code,
    'link', case when rc.code is not null then 'https://hayeva.fr/rdv?ref=' || rc.code end,
    'participant_type', rc.participant_type,
    'status', rc.status,
    'created_at', rc.created_at,
    'balances', referral_balances(p_client_id),
    'paid_year_cents', coalesce((select sum(amount_cents) from referral_payout_requests where referrer_client_id = p_client_id and status = 'PAID' and paid_at >= v_year_start), 0),
    'application', (select jsonb_build_object('no', a.public_no, 'legal_name', a.legal_name, 'siren', a.siren, 'siret', a.siret, 'status', a.status, 'approved_at', a.approved_at)
                      from referral_business_applications a where a.client_id = p_client_id order by a.created_at desc limit 1),
    'rewards', coalesce((
      select jsonb_agg(jsonb_build_object('id', w.id, 'ref', 'Client #' || rf.public_no, 'status', w.status, 'code', w.status_code,
               'reason', w.status_reason, 'flags', w.review_flags, 'amount_cents', w.amount_cents, 'paid_amount_cents', w.paid_amount_cents,
               'referee', trim(coalesce(f.first_name, '') || ' ' || coalesce(f.last_name, '')), 'booking_ref', b.reference, 'booking_status', b.status,
               'validation_source', w.validation_source, 'validated_at', w.validated_at, 'payout_no', p.public_no, 'clawback', w.clawback_alert,
               'referrer_type', w.referrer_type, 'created_at', w.created_at) order by w.created_at desc)
        from referral_rewards w join referrals rf on rf.id = w.referral_id join clients f on f.id = w.referee_client_id
        left join bookings b on b.id = w.booking_id left join referral_payout_requests p on p.id = w.payout_id
       where w.referrer_client_id = p_client_id), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at, 'refusal_reason', p.refusal_reason, 'admin_note', p.admin_note,
               'payment_reference', p.payment_reference) order by p.requested_at desc)
        from referral_payout_requests p where p.referrer_client_id = p_client_id), '[]'::jsonb),
    'ledger', coalesce((
      select jsonb_agg(jsonb_build_object('type', l.entry_type, 'amount_cents', l.amount_cents, 'created_at', l.created_at, 'detail', l.detail) order by l.created_at desc)
        from (select * from referral_ledger where referrer_client_id = p_client_id order by created_at desc limit 100) l), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_referral_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not is_admin() then raise exception 'Accès réservé à l''administration.'; end if;
  return jsonb_build_object(
    'settings', (select to_jsonb(s) - 'updated_by' from referral_settings s where s.id),
    'ambassadors_total', (select count(*) from referral_codes),
    'ambassadors_active', (select count(distinct referrer_client_id) from referral_rewards),
    'individuals_count', (select count(*) from referral_codes where participant_type = 'individual'),
    'business_count', (select count(*) from referral_codes where participant_type = 'business'),
    'suspended_count', (select count(*) from referral_codes where status = 'suspended'),
    'applications_open', (select count(*) from referral_business_applications where status in ('RECEIVED', 'TO_VERIFY')),
    'new_clients', (select count(*) from referral_rewards),
    'pending_count', (select count(*) from referral_rewards where status in ('PENDING', 'REVIEW')),
    'review_count', (select count(*) from referral_rewards where status = 'REVIEW' or (status = 'PENDING' and status_code = 'AWAITING_PAYMENT') or clawback_alert),
    'validated_count', (select count(*) from referral_rewards where status = 'VALIDATED'),
    'available_cents', coalesce((select sum(amount_cents) from referral_rewards where status = 'VALIDATED' and payout_id is null and not clawback_alert), 0),
    'payouts_requested', (select count(*) from referral_payout_requests where status in ('REQUESTED', 'REVIEWING', 'APPROVED')),
    'to_pay_cents', coalesce((select sum(amount_cents) from referral_payout_requests where status in ('REQUESTED', 'REVIEWING', 'APPROVED')), 0),
    'paid_cents', coalesce((select sum(amount_cents) from referral_payout_requests where status = 'PAID'), 0),
    'to_verify', coalesce((
      select jsonb_agg(x order by x->>'created_at') from (
        select jsonb_build_object('reward_id', rw.id, 'ref', 'Client #' || rf.public_no, 'status', rw.status, 'code', rw.status_code,
                 'reason', rw.status_reason, 'flags', rw.review_flags, 'clawback', rw.clawback_alert, 'referrer_type', rw.referrer_type,
                 'referrer', trim(coalesce(a.first_name, '') || ' ' || coalesce(a.last_name, '')), 'referrer_client_id', rw.referrer_client_id,
                 'referee', trim(coalesce(f.first_name, '') || ' ' || coalesce(f.last_name, '')),
                 'booking_ref', bk.reference, 'booking_status', bk.status, 'paid_amount_cents', rw.paid_amount_cents, 'created_at', rw.created_at) x
          from referral_rewards rw join referrals rf on rf.id = rw.referral_id
          join clients a on a.id = rw.referrer_client_id join clients f on f.id = rw.referee_client_id
          left join bookings bk on bk.id = rw.booking_id
         where rw.status = 'REVIEW' or (rw.status = 'PENDING' and rw.status_code = 'AWAITING_PAYMENT') or rw.clawback_alert) t), '[]'::jsonb),
    'payouts', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'no', p.public_no, 'amount_cents', p.amount_cents, 'status', p.status,
               'requested_at', p.requested_at, 'paid_at', p.paid_at, 'admin_note', p.admin_note, 'payment_reference', p.payment_reference,
               'referrer', trim(coalesce(a.first_name, '') || ' ' || coalesce(a.last_name, '')), 'referrer_client_id', p.referrer_client_id,
               'participant_type', (select participant_type from referral_codes where client_id = p.referrer_client_id),
               'email', a.email, 'phone', a.phone) order by p.requested_at desc)
        from referral_payout_requests p join clients a on a.id = p.referrer_client_id), '[]'::jsonb),
    'applications', coalesce((
      select jsonb_agg(jsonb_build_object('id', a.id, 'no', a.public_no, 'legal_name', a.legal_name, 'contact_name', a.contact_name,
               'email', a.email, 'phone', a.phone, 'siren', a.siren, 'siret', a.siret, 'message', a.message, 'status', a.status,
               'created_at', a.created_at, 'admin_note', a.admin_note, 'client_id', a.client_id) order by a.created_at desc)
        from (select * from referral_business_applications order by created_at desc limit 100) a), '[]'::jsonb)
  );
end;
$$;


-- Code attribué par l'administration : jamais modifiable par l'utilisateur.
create or replace function public.set_my_referral_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_client uuid; v_code text := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
begin
  v_client := public.ensure_my_client();
  if v_code !~ '^[A-Z0-9]{6,12}$' or v_code !~ '[A-Z]' then
    return jsonb_build_object('ok', false, 'error', 'FORMAT');
  end if;
  if exists (select 1 from referrals where referrer_client_id = v_client)
     or exists (select 1 from referral_codes where client_id = v_client and (created_by is not null or status <> 'active')) then
    return jsonb_build_object('ok', false, 'error', 'CODE_DEJA_UTILISE');
  end if;
  if exists (select 1 from referral_codes where code = v_code and client_id <> v_client)
     or exists (select 1 from referrals where code_used = v_code) then
    return jsonb_build_object('ok', false, 'error', 'CODE_INDISPONIBLE');
  end if;
  begin
    insert into referral_codes (client_id, code) values (v_client, v_code)
    on conflict (client_id) do update set code = excluded.code, updated_at = now();
  exception when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'CODE_INDISPONIBLE');
  end;
  return jsonb_build_object('ok', true, 'code', v_code);
end;
$$;

-- 8) Droits
revoke all on function public.referral_rewards_set_type() from public, anon, authenticated;
revoke all on function public._attach_referral(uuid, text) from public, anon, authenticated;
revoke all on function public.submit_business_referrer_application(text, text, text, text, text, text, boolean) from public;
grant execute on function public.submit_business_referrer_application(text, text, text, text, text, text, boolean) to anon, authenticated;
revoke all on function public.admin_suggest_referral_code(text) from public, anon;
revoke all on function public.admin_create_referrer(jsonb) from public, anon;
revoke all on function public.admin_set_referrer_status(uuid, text) from public, anon;
revoke all on function public.admin_set_business_application_status(uuid, text, text) from public, anon;
revoke all on function public.admin_list_referrers(text, text) from public, anon;
grant execute on function public.admin_suggest_referral_code(text), public.admin_create_referrer(jsonb), public.admin_set_referrer_status(uuid, text),
  public.admin_set_business_application_status(uuid, text, text), public.admin_list_referrers(text, text) to authenticated;
